// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Bakes the open-source default theme — the DTCG `.tokens.json` layers under
// `lib/src/themes/default/` plus its `manifest.json` (the mode → resolution-order
// wiring) — into `lib/src/default_theme.g.dart`, so the theme loads zero-IO on
// every target (no per-platform asset/file loading), exactly like the sample
// trios. The `.json` files stay the human-editable source of truth; this file is
// derived.
//
// Run from the repo root: `dart run
// packages/a2ui_craft/tool/gen_default_theme.dart`. A drift guard in
// `tool/check.sh` re-runs this and fails if the generated file is out of date.

import 'dart:convert';
import 'dart:io';

const String _root = 'packages/a2ui_craft/lib/src/themes/default';
const String _out = 'packages/a2ui_craft/lib/src/default_theme.g.dart';

void main() {
  final String manifestSource = File('$_root/manifest.json').readAsStringSync();
  final Map<String, dynamic> manifest =
      jsonDecode(manifestSource) as Map<String, dynamic>;
  final Map<String, dynamic> sets = manifest['sets'] as Map<String, dynamic>;

  final StringBuffer b = StringBuffer()
    ..writeln('// Copyright 2013 The Flutter Authors')
    ..writeln('// Use of this source code is governed by a BSD-style license '
        'that can be')
    ..writeln('// found in the LICENSE file.')
    ..writeln()
    ..writeln('// GENERATED by tool/gen_default_theme.dart — do not edit by '
        'hand.')
    ..writeln('// Source of truth: '
        'packages/a2ui_craft/lib/src/themes/default/.')
    ..writeln()
    ..writeln('/// The default theme manifest (name, sets, and the mode →')
    ..writeln('/// resolution-order wiring), as raw JSON.')
    ..writeln(
        'const String defaultThemeManifestJson = ${_raw(manifestSource)};')
    ..writeln()
    ..writeln('/// The default theme\'s DTCG token layers, keyed by set name')
    ..writeln('/// (the keys of the manifest\'s `sets`), as raw JSON.')
    ..writeln('const Map<String, String> defaultThemeSetJson '
        '= <String, String>{');

  for (final String name in sets.keys) {
    final String file = sets[name] as String;
    final String source = File('$_root/$file').readAsStringSync();
    for (final String s in <String>[manifestSource, source]) {
      if (s.contains("'''")) {
        stderr.writeln("Theme file for '$name' contains ''' — cannot "
            'raw-embed.');
        exit(1);
      }
    }
    b.writeln("  '$name': ${_raw(source)},");
  }
  b.writeln('};');

  File(_out).writeAsStringSync(b.toString());
  stdout.writeln('Generated ${sets.length} theme layers → $_out');
}

/// A raw triple-quoted Dart string literal for [s] (the theme JSON has no `'''`,
/// guarded above).
String _raw(String s) => "r'''\n$s'''";
