// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Bakes `js/driver.js` — the JavaScript driver SDK — into a Dart constant, so
// a host can hand a worker the SDK plus a driver's own source without shipping
// or fetching a second file.
//
// The `.js` file is the source of truth: it is real JavaScript, with real
// editor tooling, and it is the file a JavaScript author copies. Run from the
// repo root: `dart run packages/a2ui_craft_logic/tool/gen_driver_sdk.dart`.
// A drift guard in `tool/check.sh` re-runs this and fails if the generated
// file is stale.

import 'dart:io';

const String _source = 'packages/a2ui_craft_logic/js/driver.js';
const String _out = 'packages/a2ui_craft_logic/lib/src/driver_sdk.g.dart';

void main() {
  final String js = File(_source).readAsStringSync();
  if (js.contains("'''")) {
    stderr.writeln("driver.js contains ''' — cannot raw-embed.");
    exit(1);
  }

  File(_out).writeAsStringSync('''
// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// GENERATED by tool/gen_driver_sdk.dart — do not edit by hand.
// Source of truth: packages/a2ui_craft_logic/js/driver.js.

/// The JavaScript driver SDK, as source.
///
/// One file, no dependencies, no build step. A worker runner prepends this to a
/// driver's own source so the pair can be started from a single blob — an
/// ephemeral mini-app should not have to ship, host, or resolve a second file
/// just to speak the protocol.
///
/// A driver written against it describes itself and stops:
///
/// ```js
/// a2uiDriver({
///   onInit(ctx) { ctx.write('/status', 'ready'); },
///   handlers: {
///     addItem(ctx, event) { ctx.write('/count', 1); },
///   },
/// });
/// ```
const String driverSdkJs = r\'\'\'
$js\'\'\';
''');
  stdout.writeln('Generated the JS driver SDK → $_out');
}
