name: a2ui_craft_jaspr_example
description: An example of using A2UI Craft with Jaspr
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  a2ui_craft: ^0.0.1
  a2ui_craft_bridge: ^0.0.1
  a2ui_craft_jaspr: ^0.0.1
  jaspr: any

dev_dependencies:
  lints: ^4.0.0
