name: a2ui_craft_jaspr_example
description: An example of using A2UI Craft with Jaspr
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  a2ui_craft: ^0.0.1
  a2ui_craft_bridge: ^0.0.1
  a2ui_craft_jaspr: ^0.0.1
  a2ui_core: any
  json_schema_builder: any
  jaspr: ^0.23.1

dev_dependencies:
  build_runner: ^2.15.0
  build_web_compilers: ^4.8.4
  jaspr_builder: ^0.23.1
  jaspr_test: ^0.23.1
  lints: ^4.0.0

jaspr:
  mode: client
