// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// GENERATED by tool/gen_driver_sdk.dart — do not edit by hand.
// Source of truth: packages/a2ui_craft_logic/js/driver.js.

/// The JavaScript driver SDK, as source.
///
/// One file, no dependencies, no build step. A worker runner prepends this to a
/// driver's own source so the pair can be started from a single blob — an
/// ephemeral mini-app should not have to ship, host, or resolve a second file
/// just to speak the protocol.
///
/// A driver written against it describes itself and stops:
///
/// ```js
/// a2uiDriver({
///   onInit(ctx) { ctx.write('/status', 'ready'); },
///   handlers: {
///     addItem(ctx, event) { ctx.write('/count', 1); },
///   },
/// });
/// ```
const String driverSdkJs = r'''
// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// The A2UI Craft driver SDK for JavaScript — one file, no dependencies, no
// build step. It is the JavaScript half of the language-neutrality claim: a
// driver written against this speaks the same session protocol as one written
// in Dart, and the host cannot tell which it is talking to.
//
// Load it in a worker and describe your logic:
//
//     a2uiDriver({
//       onInit(ctx) { ctx.write('/status', 'ready'); },
//       handlers: {
//         addItem(ctx, event) { ctx.write('/count', 1); },
//       },
//     });
//
// Everything crossing the boundary is JSON. The SDK batches each handler's
// writes into one update, so a handler's effects land all at once or not at
// all, and it serializes handlers so two never interleave.

(function (global) {
  'use strict';

  var PROTOCOL_VERSION = '0.1';

  function a2uiDriver(spec) {
    var outSeq = 0;
    var inSeq = 0;
    var state = 'connecting';
    var surfaceId = null;
    var hostContext = {};
    var pending = [];
    var chain = Promise.resolve();
    var handlers = spec.handlers || {};
    var fired = {};
    var inTurn = false;

    function post(type, body) {
      if (state === 'faulted' || state === 'terminated') return;
      outSeq += 1;
      global.postMessage(JSON.stringify({
        seq: outSeq,
        type: type,
        body: body,
      }));
    }

    function fault(reason) {
      state = 'faulted';
      pending = [];
    }

    function flush() {
      if (pending.length === 0) return;
      var batch = pending;
      pending = [];
      post('update', { messages: batch });
    }

    var context = {
      get surfaceId() {
        return surfaceId;
      },
      get hostContext() {
        return hostContext;
      },
      write: function (path, value) {
        pending.push({
          version: 'v0.9',
          updateDataModel: {
            surfaceId: surfaceId,
            path: path,
            value: value,
          },
        });
        guardEscape();
      },
      send: function (messages) {
        for (var i = 0; i < messages.length; i++) pending.push(messages[i]);
        guardEscape();
      },
      fail: function (code, message, details) {
        pending = [];
        post('error', {
          code: code,
          message: message,
          details: details === undefined ? null : details,
        });
        fault(message);
      },
      diagnostic: function (message) {
        // Loud by default; a production build passes `diagnostics: false`.
        if (spec.diagnostics === false) return;
        if (global.console && global.console.warn) {
          global.console.warn('[a2ui.driver] ' + message);
        }
      },
    };

    // Catches a write that arrived after its handler already returned — a
    // promise the handler forgot to return or await:
    //
    //     handlers: {
    //       save: function (ctx) {
    //         fetch(url).then(function (r) { ctx.write('/x', r); });  // lost
    //       },
    //     }
    //
    // Left alone that write would sit in the batch until some later, unrelated
    // handler flushed it — out of order, attributed to the wrong event, or
    // never at all. So it is reported and sent on its own.
    //
    // This matters more here than in Dart: there is no `unawaited_futures`
    // lint on this side, so the runtime check is the only thing standing
    // between an author and a silent divergence.
    function guardEscape() {
      if (inTurn) return;
      context.diagnostic(
          'A write arrived outside any handler turn — a promise was probably ' +
          'not returned or awaited. It is being sent on its own rather than ' +
          "folded into the next handler's batch, but the ordering the driver " +
          'intended is lost. Return the promise from your handler.');
      flush();
    }

    // Handlers are chained, so the next event waits for this one — a driver
    // never observes two of its own handlers interleaving its state.
    function run(fn) {
      chain = chain.then(function () {
        inTurn = true;
        return fn();
      }).then(function () {
        inTurn = false;
        flush();
      }, function (error) {
        inTurn = false;
        pending = [];
        context.fail('handlerThrew', String(error));
      });
    }

    function dispatch(body) {
      var handler = handlers[body.name];
      if (!handler) {
        var known = Object.keys(handlers).sort().join(', ');
        context.diagnostic(
          "No handler for event '" + body.name + "', dispatched by '" +
          body.sourceComponentId + "'. This driver handles: " + known + '.');
        return;
      }
      fired[body.name] = true;
      return handler(context, {
        name: body.name,
        sourceComponentId: body.sourceComponentId,
        context: body.context || {},
        values: body.values || {},
        get: function (key) {
          var c = body.context || {};
          if (Object.prototype.hasOwnProperty.call(c, key)) return c[key];
          var v = body.values || {};
          return Object.prototype.hasOwnProperty.call(v, key) ? v[key] : null;
        },
      });
    }

    function receive(frame) {
      if (state === 'faulted' || state === 'terminated') return;
      if (!frame || frame.seq !== inSeq + 1) return fault('out of order');
      inSeq = frame.seq;
      var body = frame.body || {};
      switch (frame.type) {
        case 'init':
          if (state !== 'handshaking') return fault('illegal init');
          if (body.protocolVersion !== PROTOCOL_VERSION) {
            return fault('version skew');
          }
          state = 'ready';
          surfaceId = body.surfaceId;
          hostContext = body.context || {};
          if (spec.onInit) run(function () { return spec.onInit(context); });
          return;
        case 'event':
          if (state !== 'ready') return fault('illegal event');
          run(function () { return dispatch(body); });
          return;
        case 'ping':
          if (state !== 'ready') return fault('illegal ping');
          post('pong', { nonce: body.nonce });
          return;
        case 'terminate':
          state = 'terminated';
          return;
        case 'error':
          state = 'faulted';
          return;
        default:
          return fault('unknown frame type ' + frame.type);
      }
    }

    global.onmessage = function (event) {
      receive(JSON.parse(event.data));
    };

    // The driver speaks first: a worker's readiness is not observable to the
    // host, so announcing it is the only way the host learns of it.
    post('hello', { protocolVersion: PROTOCOL_VERSION, capabilities: [] });
    state = 'handshaking';
  }

  global.a2uiDriver = a2uiDriver;
})(self);
''';
