// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// GENERATED by tool/gen_default_theme.dart — do not edit by hand.
// Source of truth: packages/a2ui_craft/lib/src/themes/default/.

/// The default theme manifest (name, sets, and the mode →
/// resolution-order wiring), as raw JSON.
const String defaultThemeManifestJson = r'''
{
  "name": "A2UI Craft Default",
  "description": "The open-source default theme: the reference documentation of the semantic contract, the starter kit for custom themes, and the theming-conformance fixture. The runtime never applies it unasked (DESIGN.md §9.5).",
  "sets": {
    "base": "base.tokens.json",
    "dark": "dark.tokens.json",
    "highContrast": "light-high-contrast.tokens.json",
    "darkHighContrast": "dark-high-contrast.tokens.json",
    "roomy": "roomy.tokens.json"
  },
  "modes": {
    "light": ["base"],
    "dark": ["base", "dark"],
    "lightHighContrast": ["base", "highContrast"],
    "darkHighContrast": ["base", "dark", "darkHighContrast"]
  },
  "sizeClasses": {
    "compact": [],
    "medium": [],
    "expanded": ["roomy"],
    "large": ["roomy"],
    "extraLarge": ["roomy"]
  }
}
''';

/// The default theme's DTCG token layers, keyed by set name
/// (the keys of the manifest's `sets`), as raw JSON.
const Map<String, String> defaultThemeSetJson = <String, String>{
  'base': r'''
{
  "$description": "A2UI Craft default theme — base layer (also the Light mode). A neutral palette plus the semantic contract roles (DESIGN.md §13.4) aliased onto it, and the type scale. Mode overlays re-point the color roles onto the same palette; the type scale never changes across modes. The Light values restate the primitives the primitives hardcoded before the contract, so applying this theme in Light mode reproduces today's look.",
  "palette": {
    "$type": "color",
    "$description": "Primitive ramp. Roles alias into this; overlays override roles, not the ramp.",
    "white": { "$value": "#FFFFFF" },
    "black": { "$value": "#000000" },
    "gray": {
      "50": { "$value": "#F8F9FA" },
      "100": { "$value": "#F1F3F4" },
      "200": { "$value": "#E8EAED" },
      "300": { "$value": "#DADCE0" },
      "400": { "$value": "#BDC1C6" },
      "500": { "$value": "#9AA0A6" },
      "600": { "$value": "#80868B" },
      "700": { "$value": "#5F6368" },
      "800": { "$value": "#3C4043" },
      "900": { "$value": "#202124" }
    },
    "blue": {
      "300": { "$value": "#8AB4F8" },
      "600": { "$value": "#1A73E8" },
      "700": { "$value": "#1967D2" }
    },
    "red": {
      "300": { "$value": "#F28B82" },
      "600": { "$value": "#D93025" }
    }
  },
  "color": {
    "$type": "color",
    "$description": "The semantic contract roles (ThemeRoles). Light values.",
    "surface": { "$value": "{palette.white}" },
    "onSurface": { "$value": "{palette.gray.900}" },
    "onSurfaceVariant": { "$value": "{palette.gray.700}" },
    "primary": { "$value": "{palette.blue.600}" },
    "onPrimary": { "$value": "{palette.white}" },
    "outline": { "$value": "{palette.gray.300}" },
    "link": { "$value": "{palette.blue.600}" },
    "error": { "$value": "{palette.red.600}" },
    "onError": { "$value": "{palette.white}" }
  },
  "type": {
    "$type": "dimension",
    "$description": "Sizes only in v1 (families/weights are a later phase). Restates the primitives' built-in ramp.",
    "body": { "size": { "$value": "14px" } },
    "caption": { "size": { "$value": "12px" } },
    "heading": {
      "1": { "size": { "$value": "24px" } },
      "2": { "size": { "$value": "22px" } },
      "3": { "size": { "$value": "20px" } },
      "4": { "size": { "$value": "18px" } },
      "5": { "size": { "$value": "16px" } },
      "6": { "size": { "$value": "14px" } }
    }
  }
}
''',
  'dark': r'''
{
  "$description": "A2UI Craft default theme — Dark overlay. Layers over the base; re-points the color roles onto the base palette's darker/lighter steps. Aliases dereference after the layer merge, so overriding the role tokens here re-themes without restating the palette or the type scale.",
  "color": {
    "$type": "color",
    "surface": { "$value": "{palette.gray.900}" },
    "onSurface": { "$value": "{palette.gray.50}" },
    "onSurfaceVariant": { "$value": "{palette.gray.400}" },
    "primary": { "$value": "{palette.blue.300}" },
    "onPrimary": { "$value": "{palette.gray.900}" },
    "outline": { "$value": "{palette.gray.700}" },
    "link": { "$value": "{palette.blue.300}" },
    "error": { "$value": "{palette.red.300}" },
    "onError": { "$value": "{palette.gray.900}" }
  }
}
''',
  'highContrast': r'''
{
  "$description": "A2UI Craft default theme — Light high-contrast overlay. Layers over the base (Light); pushes foreground/border contrast to the ceiling for accessibility (WCAG AAA intent). High contrast is a first-class mode axis, not a boolean toggle on dark.",
  "color": {
    "$type": "color",
    "onSurface": { "$value": "{palette.black}" },
    "onSurfaceVariant": { "$value": "{palette.gray.900}" },
    "outline": { "$value": "{palette.gray.900}" },
    "primary": { "$value": "{palette.blue.700}" },
    "link": { "$value": "{palette.blue.700}" }
  }
}
''',
  'darkHighContrast': r'''
{
  "$description": "A2UI Craft default theme — Dark high-contrast overlay. Layers over the base AND the Dark overlay (resolution order: base, dark, dark-high-contrast), so it only carries the deltas that raise Dark's contrast: pure-black surface, pure-white ink, brighter border.",
  "color": {
    "$type": "color",
    "surface": { "$value": "{palette.black}" },
    "onSurface": { "$value": "{palette.white}" },
    "onSurfaceVariant": { "$value": "{palette.gray.100}" },
    "outline": { "$value": "{palette.gray.300}" }
  }
}
''',
  'roomy': r'''
{
  "$description": "A2UI Craft default theme — the roomy size-class overlay, applied at the expanded window size class and up (research/responsive/RESPONSIVE_DESIGN.md §4.4). Restructuring is layout; proportioning is theming: a larger screen (tablet, desktop, TV — 10-foot legibility) wants a bigger type ramp, a phone the denser base. This overlay overrides only the type scale — the size class is a second overlay axis in the cascade (mode × size class), so it composes over any mode overlay (which touches colour) without restating it.",
  "type": {
    "$type": "dimension",
    "body": { "size": { "$value": "16px" } },
    "caption": { "size": { "$value": "14px" } },
    "heading": {
      "1": { "size": { "$value": "28px" } },
      "2": { "size": { "$value": "25px" } },
      "3": { "size": { "$value": "23px" } },
      "4": { "size": { "$value": "20px" } },
      "5": { "size": { "$value": "18px" } },
      "6": { "size": { "$value": "16px" } }
    }
  }
}
''',
};
