// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Bakes the code-free sample projects (`samples/<id>/{template.craft,schema.json,
// app.json}` + `manifest.json`) into `lib/src/generated_samples.g.dart`, so
// every target (tests, the Flutter example, the Flutter-embedded view, the Jaspr
// site) reads the same in-memory strings with zero per-platform file/asset IO.
//
// Run from the repo root: `dart run
// packages/a2ui_craft_examples/tool/gen_samples.dart`. A drift guard in
// `tool/check.sh` re-runs this and fails if the generated file is out of date.

import 'dart:convert';
import 'dart:io';

const String _root = 'packages/a2ui_craft_examples/samples';
const String _miniAppRoot = 'packages/a2ui_craft_examples/mini_apps';
const String _out =
    'packages/a2ui_craft_examples/lib/src/generated_samples.g.dart';
const JsonEncoder _pretty = JsonEncoder.withIndent('  ');

void main() {
  // The gallery manifest is an ordered id list; each project's own
  // `manifest.json` holds its name (and optional catalogId / theme).
  final List<String> ids =
      (jsonDecode(File('$_root/manifest.json').readAsStringSync()) as List)
          .cast<String>();

  final StringBuffer b = StringBuffer()
    ..writeln('// Copyright 2013 The Flutter Authors')
    ..writeln('// Use of this source code is governed by a BSD-style license '
        'that can be')
    ..writeln('// found in the LICENSE file.')
    ..writeln()
    ..writeln('// GENERATED by tool/gen_samples.dart — do not edit by hand.')
    ..writeln('// Source of truth: packages/a2ui_craft_examples/samples/.')
    ..writeln()
    ..writeln("import 'sample_spec.dart';")
    ..writeln()
    ..writeln(
        '/// One sample\'s raw, code-free data (its three files), baked in')
    ..writeln('/// for zero-IO loading on every target.')
    ..writeln('class RawSample {')
    ..writeln('  const RawSample({')
    ..writeln('    required this.id,')
    ..writeln('    required this.label,')
    ..writeln('    required this.template,')
    ..writeln('    required this.schema,')
    ..writeln('    required this.messages,')
    ..writeln('    this.theme,')
    ..writeln('    this.demonstrates = const <String>[],')
    ..writeln('  });')
    ..writeln()
    ..writeln('  final String id;')
    ..writeln('  final String label;')
    ..writeln('  final String template;')
    ..writeln('  final String schema;')
    ..writeln('  final String messages;')
    ..writeln()
    ..writeln('  /// The project manifest\'s optional `theme` block (a '
        'ProjectTheme config), or null.')
    ..writeln('  final String? theme;')
    ..writeln()
    ..writeln('  /// The demonstrated-property ids from the manifest\'s '
        '`demonstrates` list')
    ..writeln('  /// (see `demo_properties.dart`); empty when the sample '
        'demonstrates none')
    ..writeln('  /// of the tracked properties.')
    ..writeln('  final List<String> demonstrates;')
    ..writeln()
    ..writeln('  /// Builds a [SampleSpec], substituting `{{framework}}`; the '
        'host supplies')
    ..writeln('  /// any action handling separately.')
    ..writeln('  SampleSpec toSpec(String framework) => SampleSpec.fromData(')
    ..writeln('        label: label,')
    ..writeln('        template: template,')
    ..writeln('        schemaJson: schema,')
    ..writeln('        messagesJson: messages,')
    ..writeln('        framework: framework,')
    ..writeln('        themeJson: theme,')
    ..writeln('      );')
    ..writeln('}')
    ..writeln()
    ..writeln('/// Every built-in sample, in gallery order.')
    ..writeln('const List<RawSample> rawSamples = <RawSample>[');

  for (final String id in ids) {
    // The project manifest consolidates name + optional catalogId + theme.
    final Map<String, dynamic> project =
        jsonDecode(File('$_root/$id/manifest.json').readAsStringSync())
            as Map<String, dynamic>;
    final String label = project['name'] as String;
    final String template =
        File('$_root/$id/template.craft').readAsStringSync();
    final String schema = File('$_root/$id/schema.json').readAsStringSync();
    // app.json is the mini-app bootstrap — the canned A2UI message stream that
    // builds the surface with no agent (an agent-driven project omits it).
    final String messages = File('$_root/$id/app.json').readAsStringSync();
    // The theme is the manifest's optional `theme` block (a ProjectTheme
    // config) — present only for themed projects; re-encoded as its own JSON.
    final Object? themeConfig = project['theme'];
    final String? theme =
        themeConfig == null ? null : '${_pretty.convert(themeConfig)}\n';
    // The manifest's demonstrated-property labels (demo-catalog metadata).
    final List<String> demonstrates =
        (project['demonstrates'] as List<dynamic>? ?? <dynamic>[]).cast();
    for (final String? s in <String?>[template, schema, messages, theme]) {
      if (s != null && s.contains("'''")) {
        stderr.writeln("Sample '$id' contains ''' — cannot raw-embed.");
        exit(1);
      }
    }
    b
      ..writeln('  RawSample(')
      ..writeln("    id: '$id',")
      ..writeln('    label: ${_dartString(label)},')
      ..writeln("    template: r'''")
      ..write(template)
      ..writeln("''',")
      ..writeln("    schema: r'''")
      ..write(schema)
      ..writeln("''',")
      ..writeln("    messages: r'''")
      ..write(messages)
      ..writeln("''',");
    if (theme != null) {
      b
        ..writeln("    theme: r'''")
        ..write(theme)
        ..writeln("''',");
    }
    if (demonstrates.isNotEmpty) {
      final String items = demonstrates.map((String d) => "'$d'").join(', ');
      b.writeln('    demonstrates: <String>[$items],');
    }
    b.writeln('  ),');
  }
  b
    ..writeln('];')
    ..writeln()
    ..writeln('// Named accessors (one per sample), kept for the example apps '
        'and tests.');
  for (int i = 0; i < ids.length; i++) {
    final String name = _camel(ids[i]);
    b.writeln('SampleSpec ${name}Spec(String framework) => '
        'rawSamples[$i].toSpec(framework);');
  }

  _writeMiniApps(b);

  File(_out).writeAsStringSync(b.toString());
  stdout.writeln('Generated ${ids.length} samples → $_out');
}

/// Bakes the **mini-apps** — projects that ship business logic, so unlike a
/// sample they are not renderable on their own. They live outside `samples/`
/// and outside the gallery for exactly that reason: a mini-app without its
/// driver is not a degraded demo, it is a screen of controls that answer
/// nothing.
void _writeMiniApps(StringBuffer b) {
  final List<String> ids =
      (jsonDecode(File('$_miniAppRoot/manifest.json').readAsStringSync())
              as List)
          .cast<String>();

  b
    ..writeln()
    ..writeln("/// One mini-app's project data: the same three files a sample")
    ..writeln('/// has, plus the manifest `logic` slot naming the driver that')
    ..writeln('/// answers its events.')
    ..writeln('class RawMiniApp {')
    ..writeln('  const RawMiniApp({')
    ..writeln('    required this.id,')
    ..writeln('    required this.label,')
    ..writeln('    required this.template,')
    ..writeln('    required this.schema,')
    ..writeln('    required this.messages,')
    ..writeln('    required this.logic,')
    ..writeln('    required this.driverJs,')
    ..writeln('  });')
    ..writeln()
    ..writeln('  final String id;')
    ..writeln('  final String label;')
    ..writeln('  final String template;')
    ..writeln('  final String schema;')
    ..writeln()
    ..writeln('  /// The recorded Transport stream that cold-boots the')
    ..writeln('  /// surface before any driver connects.')
    ..writeln('  final String messages;')
    ..writeln()
    ..writeln("  /// The manifest's `logic` block, as JSON.")
    ..writeln('  final String logic;')
    ..writeln()
    ..writeln('  /// The JavaScript driver, as source — the portable half of')
    ..writeln('  /// the mini-app, runnable in a worker on any host.')
    ..writeln('  final String driverJs;')
    ..writeln()
    ..writeln('  /// The renderable half of the project.')
    ..writeln('  SampleSpec toSpec() => SampleSpec.fromData(')
    ..writeln('        label: label,')
    ..writeln('        template: template,')
    ..writeln('        schemaJson: schema,')
    ..writeln('        messagesJson: messages,')
    ..writeln('      );')
    ..writeln('}')
    ..writeln()
    ..writeln('/// Every built-in mini-app.')
    ..writeln('const List<RawMiniApp> rawMiniApps = <RawMiniApp>[');

  for (final String id in ids) {
    final Map<String, dynamic> project =
        jsonDecode(File('$_miniAppRoot/$id/manifest.json').readAsStringSync())
            as Map<String, dynamic>;
    final String template =
        File('$_miniAppRoot/$id/template.craft').readAsStringSync();
    final String schema =
        File('$_miniAppRoot/$id/schema.json').readAsStringSync();
    final String messages =
        File('$_miniAppRoot/$id/app.json').readAsStringSync();
    final String logic = '${_pretty.convert(project['logic'])}\n';
    final String driverJs = File(
            '$_miniAppRoot/$id/${(project['logic'] as Map<String, dynamic>)['entry']}')
        .readAsStringSync();
    for (final String s in <String>[
      template,
      schema,
      messages,
      logic,
      driverJs
    ]) {
      if (s.contains("'''")) {
        stderr.writeln("Mini-app '$id' contains ''' — cannot raw-embed.");
        exit(1);
      }
    }
    b
      ..writeln('  RawMiniApp(')
      ..writeln("    id: '$id',")
      ..writeln('    label: ${_dartString(project['name'] as String)},')
      ..writeln("    template: r'''")
      ..write(template)
      ..writeln("''',")
      ..writeln("    schema: r'''")
      ..write(schema)
      ..writeln("''',")
      ..writeln("    messages: r'''")
      ..write(messages)
      ..writeln("''',")
      ..writeln("    logic: r'''")
      ..write(logic)
      ..writeln("''',")
      ..writeln("    driverJs: r'''")
      ..write(driverJs)
      ..writeln("''',")
      ..writeln('  ),');
  }
  b.writeln('];');
  for (int i = 0; i < ids.length; i++) {
    b
      ..writeln()
      ..writeln('/// The `${ids[i]}` mini-app.')
      ..writeln('final RawMiniApp ${_camel(ids[i])}MiniApp = rawMiniApps[$i];');
  }
}

String _camel(String snake) {
  final List<String> parts = snake.split('_');
  return parts.first +
      parts
          .skip(1)
          .map((String p) =>
              p.isEmpty ? '' : p[0].toUpperCase() + p.substring(1))
          .join();
}

String _dartString(String s) =>
    "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'")}'";
