// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Bakes the code-free sample trios (`samples/<id>/{template.craft,schema.json,
// messages.json}` + `manifest.json`) into `lib/src/generated_samples.g.dart`, so
// every target (tests, the Flutter example, the Flutter-embedded view, the Jaspr
// site) reads the same in-memory strings with zero per-platform file/asset IO.
//
// Run from the repo root: `dart run
// packages/a2ui_craft_examples/tool/gen_samples.dart`. A drift guard in
// `tool/check.sh` re-runs this and fails if the generated file is out of date.

import 'dart:convert';
import 'dart:io';

const String _root = 'packages/a2ui_craft_examples/samples';
const String _out =
    'packages/a2ui_craft_examples/lib/src/generated_samples.g.dart';

void main() {
  final List<Map<String, dynamic>> manifest =
      (jsonDecode(File('$_root/manifest.json').readAsStringSync()) as List)
          .cast<Map<String, dynamic>>();

  final StringBuffer b = StringBuffer()
    ..writeln('// Copyright 2013 The Flutter Authors')
    ..writeln('// Use of this source code is governed by a BSD-style license '
        'that can be')
    ..writeln('// found in the LICENSE file.')
    ..writeln()
    ..writeln('// GENERATED by tool/gen_samples.dart — do not edit by hand.')
    ..writeln('// Source of truth: packages/a2ui_craft_examples/samples/.')
    ..writeln()
    ..writeln("import 'sample_spec.dart';")
    ..writeln()
    ..writeln(
        '/// One sample\'s raw, code-free data (its three files), baked in')
    ..writeln('/// for zero-IO loading on every target.')
    ..writeln('class RawSample {')
    ..writeln('  const RawSample({')
    ..writeln('    required this.id,')
    ..writeln('    required this.label,')
    ..writeln('    required this.template,')
    ..writeln('    required this.schema,')
    ..writeln('    required this.messages,')
    ..writeln('  });')
    ..writeln()
    ..writeln('  final String id;')
    ..writeln('  final String label;')
    ..writeln('  final String template;')
    ..writeln('  final String schema;')
    ..writeln('  final String messages;')
    ..writeln()
    ..writeln('  /// Builds a [SampleSpec], substituting `{{framework}}`; the '
        'host supplies')
    ..writeln('  /// any action handling separately.')
    ..writeln('  SampleSpec toSpec(String framework) => SampleSpec.fromData(')
    ..writeln('        label: label,')
    ..writeln('        template: template,')
    ..writeln('        schemaJson: schema,')
    ..writeln('        messagesJson: messages,')
    ..writeln('        framework: framework,')
    ..writeln('      );')
    ..writeln('}')
    ..writeln()
    ..writeln('/// Every built-in sample, in gallery order.')
    ..writeln('const List<RawSample> rawSamples = <RawSample>[');

  for (final Map<String, dynamic> m in manifest) {
    final String id = m['id'] as String;
    final String label = m['label'] as String;
    final String template =
        File('$_root/$id/template.craft').readAsStringSync();
    final String schema = File('$_root/$id/schema.json').readAsStringSync();
    final String messages = File('$_root/$id/messages.json').readAsStringSync();
    for (final String s in <String>[template, schema, messages]) {
      if (s.contains("'''")) {
        stderr.writeln("Sample '$id' contains ''' — cannot raw-embed.");
        exit(1);
      }
    }
    b
      ..writeln('  RawSample(')
      ..writeln("    id: '$id',")
      ..writeln('    label: ${_dartString(label)},')
      ..writeln("    template: r'''")
      ..write(template)
      ..writeln("''',")
      ..writeln("    schema: r'''")
      ..write(schema)
      ..writeln("''',")
      ..writeln("    messages: r'''")
      ..write(messages)
      ..writeln("''',")
      ..writeln('  ),');
  }
  b
    ..writeln('];')
    ..writeln()
    ..writeln('// Named accessors (one per sample), kept for the example apps '
        'and tests.');
  for (int i = 0; i < manifest.length; i++) {
    final String name = _camel(manifest[i]['id'] as String);
    b.writeln('SampleSpec ${name}Spec(String framework) => '
        'rawSamples[$i].toSpec(framework);');
  }

  File(_out).writeAsStringSync(b.toString());
  stdout.writeln('Generated ${manifest.length} samples → $_out');
}

String _camel(String snake) {
  final List<String> parts = snake.split('_');
  return parts.first +
      parts
          .skip(1)
          .map((String p) =>
              p.isEmpty ? '' : p[0].toUpperCase() + p.substring(1))
          .join();
}

String _dartString(String s) =>
    "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'")}'";
