// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// GENERATED by tool/gen_samples.dart — do not edit by hand.
// Source of truth: packages/a2ui_craft_examples/samples/.

import 'sample_spec.dart';

/// One sample's raw, code-free data (its three files), baked in
/// for zero-IO loading on every target.
class RawSample {
  const RawSample({
    required this.id,
    required this.label,
    required this.template,
    required this.schema,
    required this.messages,
  });

  final String id;
  final String label;
  final String template;
  final String schema;
  final String messages;

  /// Builds a [SampleSpec], substituting `{{framework}}`; the host supplies
  /// any action handling separately.
  SampleSpec toSpec(String framework) => SampleSpec.fromData(
        label: label,
        template: template,
        schemaJson: schema,
        messagesJson: messages,
        framework: framework,
      );
}

/// Every built-in sample, in gallery order.
const List<RawSample> rawSamples = <RawSample>[
  RawSample(
    id: 'greeting',
    label: 'Greeting',
    template: r'''
import core;

widget Greeting = Column(children: [
  Text(text: args.title),
  Text(text: args.message),
  Button(onPressed: args.action, child: Text(text: args.buttonLabel)),
]);
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "Greeting": {
      "properties": {
        "title": {
          "$ref": "DynamicString"
        },
        "message": {
          "$ref": "DynamicString"
        },
        "buttonLabel": {
          "$ref": "DynamicString"
        },
        "action": {
          "$ref": "Action"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateDataModel": {
      "surfaceId": "demo",
      "path": "/",
      "value": {
        "greeting": "Press the button."
      }
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "Greeting",
          "title": "A2UI Craft × {{framework}}",
          "message": {
            "path": "/greeting"
          },
          "buttonLabel": "Say hi",
          "action": {
            "event": {
              "name": "greet",
              "context": {}
            }
          }
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'counter',
    label: 'Counter',
    template: r'''
import core;

// A counter that counts purely in-template: local `count` state, incremented by
// `set state.count = add(...)`. RFW has no `+` operator, so the `+ 1` is a call
// to the standard `add` function. No host code, no data-model round-trip, and no
// agent in the loop — the same behavior on every adapter (see DESIGN.md, the
// template-functions slice).
widget Counter { count: 0 } = Column(children: [
  Text(text: args.label),
  Text(text: state.count),
  Button(
    onPressed: set state.count = add(a: state.count, b: 1),
    child: Text(text: args.buttonLabel),
  ),
]);
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "Counter": {
      "properties": {
        "label": {
          "$ref": "DynamicString"
        },
        "buttonLabel": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "Counter",
          "label": "You have pushed the button this many times:",
          "buttonLabel": "Increment"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'toggle',
    label: 'Toggle',
    template: r'''
import core;

// A stateful template — interactivity with no host code. `{ open: false }`
// declares local state; the button flips it with `set state.open = switch ...`
// (RFW has no `!` operator, so the flip is a switch); and `switch state.open`
// chooses what renders. The same template drives both the Flutter and Jaspr
// renderers identically.
widget Toggle { open: false } =
  Card(child: Column(crossAxisAlignment: "start", gap: 8.0, children: [
    Heading(text: args.question, level: 3),
    Button(
      onPressed: set state.open = switch state.open { true: false, default: true },
      child: Text(
        text: switch state.open { true: "Hide answer", default: "Show answer" },
      ),
    ),
    Text(text: switch state.open { true: args.answer, default: "" }),
  ]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "Toggle": {
      "properties": {
        "question": {
          "$ref": "DynamicString"
        },
        "answer": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "Toggle",
          "question": "Does this run without host code?",
          "answer": "Yes — the show/hide is pure template state (RFW `set state` + `switch`), re-rendered identically by the {{framework}} adapter. No Dart, no data-model round-trip, no agent in the loop."
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'calculator',
    label: 'Calculator',
    template: r'''
import core;

// A four-function calculator computed entirely in-template — no host code, no
// data-model round-trip, no agent. It leans on the standard math functions (RFW
// has no arithmetic operators) plus local state:
//
//   display — the operand currently being typed
//   acc     — the accumulated result of the pending operation
//   op      — the pending operator ("add"/"subtract"/"multiply"/"divide", or "")
//
// A digit key appends by `display * 10 + d`. An operator key commits the pending
// operation into `acc` (a `switch` over `op` picks the right function), remembers
// the new operator, and clears `display` for the next operand — three state
// writes in one press. Equals applies the pending operation. It behaves
// identically on the Flutter and Jaspr adapters.

// One key: a button showing [label] that runs [press] (a `set state`, or a list
// of them). The handler is passed in as an arg, so the state stays on the
// Calculator and the key itself is stateless.
widget Key = Button(
  onPressed: args.press,
  child: Box(
    width: 46.0,
    height: 44.0,
    color: args.color,
    child: Center(child: Text(text: args.label)),
  ),
);

widget Calculator { display: 0, acc: 0, op: "" } = Card(child: Column(
  crossAxisAlignment: "center",
  gap: 6.0,
  children: [
    // Display: the current operand, right-aligned.
    Box(
      width: 202.0,
      padding: [10.0, 12.0, 10.0, 12.0],
      color: "#f1f5f9",
      child: Row(mainAxisAlignment: "end", width: "fill", children: [
        Heading(text: state.display, level: 2),
      ]),
    ),
    Row(gap: 6.0, children: [
      Key(label: "7", color: "#e2e8f0",
        press: set state.display = add(a: multiply(a: state.display, b: 10), b: 7)),
      Key(label: "8", color: "#e2e8f0",
        press: set state.display = add(a: multiply(a: state.display, b: 10), b: 8)),
      Key(label: "9", color: "#e2e8f0",
        press: set state.display = add(a: multiply(a: state.display, b: 10), b: 9)),
      Key(label: "÷", color: "#cbd5e1", press: [
        set state.acc = switch state.op {
          "add": add(a: state.acc, b: state.display),
          "subtract": subtract(a: state.acc, b: state.display),
          "multiply": multiply(a: state.acc, b: state.display),
          "divide": divide(a: state.acc, b: state.display),
          default: state.display
        },
        set state.op = "divide",
        set state.display = 0,
      ]),
    ]),
    Row(gap: 6.0, children: [
      Key(label: "4", color: "#e2e8f0",
        press: set state.display = add(a: multiply(a: state.display, b: 10), b: 4)),
      Key(label: "5", color: "#e2e8f0",
        press: set state.display = add(a: multiply(a: state.display, b: 10), b: 5)),
      Key(label: "6", color: "#e2e8f0",
        press: set state.display = add(a: multiply(a: state.display, b: 10), b: 6)),
      Key(label: "×", color: "#cbd5e1", press: [
        set state.acc = switch state.op {
          "add": add(a: state.acc, b: state.display),
          "subtract": subtract(a: state.acc, b: state.display),
          "multiply": multiply(a: state.acc, b: state.display),
          "divide": divide(a: state.acc, b: state.display),
          default: state.display
        },
        set state.op = "multiply",
        set state.display = 0,
      ]),
    ]),
    Row(gap: 6.0, children: [
      Key(label: "1", color: "#e2e8f0",
        press: set state.display = add(a: multiply(a: state.display, b: 10), b: 1)),
      Key(label: "2", color: "#e2e8f0",
        press: set state.display = add(a: multiply(a: state.display, b: 10), b: 2)),
      Key(label: "3", color: "#e2e8f0",
        press: set state.display = add(a: multiply(a: state.display, b: 10), b: 3)),
      Key(label: "−", color: "#cbd5e1", press: [
        set state.acc = switch state.op {
          "add": add(a: state.acc, b: state.display),
          "subtract": subtract(a: state.acc, b: state.display),
          "multiply": multiply(a: state.acc, b: state.display),
          "divide": divide(a: state.acc, b: state.display),
          default: state.display
        },
        set state.op = "subtract",
        set state.display = 0,
      ]),
    ]),
    Row(gap: 6.0, children: [
      Key(label: "C", color: "#fca5a5", press: [
        set state.display = 0,
        set state.acc = 0,
        set state.op = "",
      ]),
      Key(label: "0", color: "#e2e8f0",
        press: set state.display = multiply(a: state.display, b: 10)),
      Key(label: "=", color: "#86efac", press: [
        set state.display = switch state.op {
          "add": add(a: state.acc, b: state.display),
          "subtract": subtract(a: state.acc, b: state.display),
          "multiply": multiply(a: state.acc, b: state.display),
          "divide": divide(a: state.acc, b: state.display),
          default: state.display
        },
        set state.op = "",
        set state.acc = 0,
      ]),
      Key(label: "+", color: "#cbd5e1", press: [
        set state.acc = switch state.op {
          "add": add(a: state.acc, b: state.display),
          "subtract": subtract(a: state.acc, b: state.display),
          "multiply": multiply(a: state.acc, b: state.display),
          "divide": divide(a: state.acc, b: state.display),
          default: state.display
        },
        set state.op = "add",
        set state.display = 0,
      ]),
    ]),
  ],
));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "Calculator": {
      "properties": {}
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "Calculator"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'boxes',
    label: 'Boxes',
    template: r'''
import core;

widget Boxes = Column(gap: 20, children: [
  Text(text: "Here are some nested boxes with margins and padding:"),
  Box(
    padding: [20.0, 20.0, 20.0, 20.0],
    color: "#e2e8f0",
    child: Box(
      width: 100.0,
      height: 100.0,
      color: "#94a3b8",
      child: Box(
        margin: [10.0, 10.0, 10.0, 10.0],
        width: "fill",
        height: "fill",
        color: "#334155",
        child: Center(
          child: Text(text: "Center")
        )
      )
    )
  ),
  Box(
    margin: [20.0, 0.0, 0.0, 0.0],
    padding: [10.0, 10.0, 10.0, 10.0],
    color: "#cbd5e1",
    child: Row(gap: 10, children: [
      Box(width: 50.0, height: 50.0, color: "#ef4444"),
      Box(width: 50.0, height: 50.0, color: "#10b981"),
      Box(width: 50.0, height: 50.0, color: "#3b82f6"),
    ])
  )
]);
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "Boxes": {
      "properties": {}
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "Boxes"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'layout',
    label: 'Layout',
    template: r'''
import core;

widget LayoutDemo = Column(gap: 12, children: [
  Text(text: "Layout primitives (same on every adapter):"),

  Text(text: "Align — anchored bottom-right in a fixed box:", variant: "caption"),
  Box(width: 200.0, height: 60.0, color: "#e2e8f0",
    child: Align(alignment: "bottomRight", width: 200.0, height: 60.0,
      child: Box(width: 40.0, height: 30.0, color: "#3b82f6"))),

  Text(text: "AspectRatio — height derived from width (2.5:1):", variant: "caption"),
  SizedBox(width: 200.0,
    child: AspectRatio(ratio: 2.5,
      child: Box(width: "fill", height: "fill", color: "#10b981"))),

  Text(text: "Wrap — chips flow and wrap to the next run:", variant: "caption"),
  SizedBox(width: 260.0,
    child: Wrap(gap: 8.0, runGap: 8.0, children: [
      Box(width: 70.0, height: 30.0, color: "#fca5a5"),
      Box(width: 70.0, height: 30.0, color: "#fcd34d"),
      Box(width: 70.0, height: 30.0, color: "#86efac"),
      Box(width: 70.0, height: 30.0, color: "#93c5fd"),
    ])),

  Text(text: "Opacity — child faded to 35%:", variant: "caption"),
  Opacity(opacity: 0.35,
    child: Box(width: 140.0, height: 36.0, color: "#7c3aed",
      child: Center(child: Text(text: "faded")))),
]);
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "LayoutDemo": {
      "properties": {}
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "LayoutDemo"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'contact_card',
    label: 'Contact Card',
    template: r'''
import core;

widget ContactCard = Card(
  child: Column(crossAxisAlignment: "center", gap: 8.0, children: [
    Image(url: args.avatar, variant: "avatar", fit: "cover"),
    Text(text: args.name),
    Text(text: args.title, variant: "caption"),
    Divider(),
    Column(gap: 6.0, children: [
      Row(gap: 8.0, children: [Icon(icon: "phone"), Text(text: args.phone)]),
      Row(gap: 8.0, children: [Icon(icon: "email"), Text(text: args.email)]),
      Row(gap: 8.0,
          children: [Icon(icon: "location"), Text(text: args.location)]),
    ]),
  ]),
);
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "ContactCard": {
      "properties": {
        "name": {
          "$ref": "DynamicString"
        },
        "title": {
          "$ref": "DynamicString"
        },
        "avatar": {
          "$ref": "DynamicString"
        },
        "phone": {
          "$ref": "DynamicString"
        },
        "email": {
          "$ref": "DynamicString"
        },
        "location": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "ContactCard",
          "name": "Ada Lovelace",
          "title": "Mathematician",
          "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
          "phone": "+1 555 0100",
          "email": "ada@example.com",
          "location": "London, UK"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'stats_card',
    label: 'Stats Card',
    template: r'''
import core;

widget Stat = Column(crossAxisAlignment: "center", children: [
  Text(text: args.value),
  Text(text: args.label, variant: "caption"),
]);

widget StatsCard = Box(width: 300.0, child: Card(child: Column(gap: 12.0, children: [
  Row(mainAxisAlignment: "spaceBetween", width: "fill", children: [
    Text(text: args.title),
    Icon(icon: "favorite"),
  ]),
  Divider(),
  Row(mainAxisAlignment: "spaceAround", width: "fill", children: [
    Stat(value: args.steps, label: "steps"),
    Stat(value: args.calories, label: "kcal"),
    Stat(value: args.minutes, label: "min"),
  ]),
  Text(text: "Daily goal: 70%", variant: "caption"),
  Slider(value: 70.0, min: 0.0, max: 100.0),
])));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "Stat": {
      "properties": {
        "value": {
          "$ref": "DynamicString"
        },
        "label": {
          "$ref": "DynamicString"
        }
      }
    },
    "StatsCard": {
      "properties": {
        "title": {
          "$ref": "DynamicString"
        },
        "steps": {
          "$ref": "DynamicString"
        },
        "calories": {
          "$ref": "DynamicString"
        },
        "minutes": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "StatsCard",
          "title": "Today's Activity",
          "steps": "8,420",
          "calories": "612",
          "minutes": "47"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'profile_card',
    label: 'Profile Card',
    template: r'''
import core;

widget ProfileCard = Card(child: Column(children: [
  Image(url: args.avatarUrl),
  Row(children: [
    Text(text: args.name),
    Icon(icon: "check"),
  ]),
  Divider(),
  Text(text: args.bio),
]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "Column": {
      "properties": {
        "children": {
          "$ref": "ChildList"
        }
      },
      "required": [
        "children"
      ]
    },
    "ProfileCard": {
      "properties": {
        "name": {
          "$ref": "DynamicString"
        },
        "avatarUrl": {
          "$ref": "DynamicString"
        },
        "bio": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "Column",
          "crossAxisAlignment": "stretch",
          "gap": 8.0,
          "children": [
            "p1",
            "p2"
          ]
        },
        {
          "id": "p1",
          "component": "ProfileCard",
          "name": "{{framework}} Framework",
          "avatarUrl": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=50&h=50&fit=crop",
          "bio": "Build apps for any screen."
        },
        {
          "id": "p2",
          "component": "ProfileCard",
          "name": "Dart",
          "avatarUrl": "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=50&h=50&fit=crop",
          "bio": "A client-optimized language for fast apps on any platform."
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'gallery',
    label: 'Image Gallery',
    template: r'''
import core;

widget Gallery = ScrollView(child: Column(children: [
  ...for url in args.images: Image(url: url),
]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "Gallery": {
      "properties": {
        "images": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "Gallery",
          "images": [
            "https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=50&h=50&fit=crop",
            "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=50&h=50&fit=crop",
            "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=50&h=50&fit=crop"
          ]
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'form',
    label: 'Form',
    template: r'''
import core;

widget Stack = Column(children: args.children);
widget Label = Text(text: args.text);
widget Field = Column(children: [
  Text(text: args.label, variant: "caption"),
  TextField(value: args.value, onChanged: args.setValue),
]);
widget Toggle = Checkbox(value: args.value, onChanged: args.setValue);
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "Stack": {
      "properties": {
        "children": {
          "$ref": "ChildList"
        }
      },
      "required": [
        "children"
      ]
    },
    "Label": {
      "properties": {
        "text": {
          "$ref": "DynamicString"
        }
      },
      "required": [
        "text"
      ]
    },
    "Field": {
      "properties": {
        "label": {
          "$ref": "DynamicString"
        },
        "value": {
          "$ref": "DynamicString"
        }
      }
    },
    "Toggle": {
      "properties": {
        "value": {
          "$ref": "DynamicBoolean"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateDataModel": {
      "surfaceId": "demo",
      "path": "/",
      "value": {
        "name": "",
        "agree": false
      }
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "Stack",
          "children": [
            "field",
            "greeting",
            "toggle"
          ]
        },
        {
          "id": "field",
          "component": "Field",
          "label": "Your name",
          "value": {
            "path": "/name"
          }
        },
        {
          "id": "greeting",
          "component": "Label",
          "text": {
            "path": "/name"
          }
        },
        {
          "id": "toggle",
          "component": "Toggle",
          "value": {
            "path": "/agree"
          }
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'simple_text',
    label: 'Simple Text',
    template: r'''
import core;

widget SimpleText = Text(text: args.text);
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "SimpleText": {
      "properties": {
        "text": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "SimpleText",
          "text": "Hello, Minimal Catalog!"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'interactive_button',
    label: 'Interactive Button',
    template: r'''
import core;

// `width: "fill"` gives the column cross-axis space so `crossAxisAlignment:
// center` actually centers (a hug-width column has nothing to center within).
// Without it the two adapters diverge: Jaspr's hug cross resolves to CSS `auto`
// and fills the parent (centering shows), while Flutter hugs to its widest child
// and sits at the start (centering is a no-op).
widget InteractiveButton = Column(crossAxisAlignment: "center",
  mainAxisAlignment: "center", width: "fill", gap: 12.0, children: [
    Text(text: args.prompt),
    Button(child: Text(text: args.label)),
  ]);
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "InteractiveButton": {
      "properties": {
        "prompt": {
          "$ref": "DynamicString"
        },
        "label": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "InteractiveButton",
          "prompt": "Click the button below",
          "label": "Click Me"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'login_form',
    label: 'Login Form',
    template: r'''
import core;

widget Labelled = Column(gap: 4.0, children: [
  Text(text: args.label, variant: "caption"),
  TextField(value: args.value),
]);

widget LoginForm = Column(gap: 12.0, crossAxisAlignment: "stretch", children: [
  Text(text: args.title),
  Labelled(label: args.usernameLabel, value: args.username),
  Labelled(label: args.passwordLabel, value: args.password),
  Button(child: Text(text: args.submitLabel)),
]);
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "Labelled": {
      "properties": {
        "label": {
          "$ref": "DynamicString"
        },
        "value": {
          "$ref": "DynamicString"
        }
      }
    },
    "LoginForm": {
      "properties": {
        "title": {
          "$ref": "DynamicString"
        },
        "usernameLabel": {
          "$ref": "DynamicString"
        },
        "username": {
          "$ref": "DynamicString"
        },
        "passwordLabel": {
          "$ref": "DynamicString"
        },
        "password": {
          "$ref": "DynamicString"
        },
        "submitLabel": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "LoginForm",
          "title": "Login",
          "usernameLabel": "Username",
          "username": "",
          "passwordLabel": "Password",
          "password": "",
          "submitLabel": "Sign In"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'weather',
    label: 'Weather',
    template: r'''
import core;

widget Weather = Card(child: Column(crossAxisAlignment: "center", gap: 6.0,
  children: [
    Row(gap: 8.0, children: [
      Text(text: args.tempHigh),
      Text(text: args.tempLow, variant: "caption"),
    ]),
    Text(text: args.location),
    Text(text: args.description, variant: "caption"),
    Row(mainAxisAlignment: "spaceAround", width: "fill", gap: 12.0, children: [
      ...for day in args.forecast: Column(crossAxisAlignment: "center",
        gap: 2.0, children: [
          Text(text: day.name, variant: "caption"),
          Text(text: day.icon),
          Text(text: day.temp, variant: "caption"),
        ]),
    ]),
  ]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "Weather": {
      "properties": {
        "tempHigh": {
          "$ref": "DynamicString"
        },
        "tempLow": {
          "$ref": "DynamicString"
        },
        "location": {
          "$ref": "DynamicString"
        },
        "description": {
          "$ref": "DynamicString"
        },
        "forecast": {
          "type": "array",
          "items": {
            "type": "object"
          }
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "Weather",
          "tempHigh": "72°",
          "tempLow": "58°",
          "location": "Austin, TX",
          "description": "Clear skies with light breeze",
          "forecast": [
            {
              "name": "Mon",
              "icon": "☀",
              "temp": "74°"
            },
            {
              "name": "Tue",
              "icon": "☀",
              "temp": "76°"
            },
            {
              "name": "Wed",
              "icon": "⛅",
              "temp": "71°"
            },
            {
              "name": "Thu",
              "icon": "☀",
              "temp": "73°"
            },
            {
              "name": "Fri",
              "icon": "☀",
              "temp": "75°"
            }
          ]
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'product_card',
    label: 'Product Card',
    template: r'''
import core;

// An interactive product card. `qty` is local state; a stepper (− / +) adjusts it
// (clamped at 1 with `max`), and the line total is computed live from a numeric
// unit price with the math functions: multiply by the quantity, then divide by
// 100 to render cents as dollars. Prices are integer cents so the arithmetic is
// exact; the single divide-by-100 formats the dollars.
widget ProductCard { qty: 1 } = Card(child: Column(gap: 8.0, children: [
  Image(url: args.imageUrl, variant: "mediumFeature", fit: "cover"),
  Text(text: args.name),
  Row(gap: 6.0, crossAxisAlignment: "center", children: [
    Text(text: args.stars),
    Text(text: args.reviews, variant: "caption"),
  ]),
  Row(gap: 8.0, crossAxisAlignment: "center", children: [
    Text(text: concat(a: "$", b: divide(a: args.unitPrice, b: 100))),
    Text(text: args.originalPrice, variant: "caption"),
  ]),
  Divider(),
  Row(mainAxisAlignment: "spaceBetween", crossAxisAlignment: "center",
    width: "fill", children: [
      Text(text: "Quantity", variant: "caption"),
      Row(gap: 12.0, crossAxisAlignment: "center", children: [
        Button(
          onPressed: set state.qty = max(a: subtract(a: state.qty, b: 1), b: 1),
          child: Text(text: "−")),
        Text(text: state.qty),
        Button(
          onPressed: set state.qty = add(a: state.qty, b: 1),
          child: Text(text: "+")),
      ]),
    ]),
  Row(mainAxisAlignment: "spaceBetween", width: "fill", children: [
    Text(text: "Total"),
    Text(text: concat(a: "$",
      b: divide(a: multiply(a: args.unitPrice, b: state.qty), b: 100))),
  ]),
  Button(child: Text(text: args.cta)),
]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "ProductCard": {
      "properties": {
        "imageUrl": {
          "$ref": "DynamicString"
        },
        "name": {
          "$ref": "DynamicString"
        },
        "stars": {
          "$ref": "DynamicString"
        },
        "reviews": {
          "$ref": "DynamicString"
        },
        "unitPrice": {
          "type": "integer"
        },
        "originalPrice": {
          "$ref": "DynamicString"
        },
        "cta": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "ProductCard",
          "imageUrl": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=300&h=200&fit=crop",
          "name": "Wireless Headphones Pro",
          "stars": "★★★★★",
          "reviews": "(2,847 reviews)",
          "unitPrice": 19999,
          "originalPrice": "$249.99",
          "cta": "Add to Cart"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'restaurant_card',
    label: 'Restaurant Card',
    template: r'''
import core;

widget RestaurantCard = Card(child: Column(gap: 8.0, children: [
  Image(url: args.image, variant: "header", fit: "cover"),
  Column(gap: 6.0, children: [
    Row(mainAxisAlignment: "spaceBetween", crossAxisAlignment: "center",
      width: "fill", children: [
        Text(text: args.name),
        Text(text: args.priceRange),
      ]),
    Text(text: args.cuisine, variant: "caption"),
    Row(gap: 6.0, crossAxisAlignment: "center", children: [
      Icon(icon: "star"),
      Text(text: args.rating),
      Text(text: args.reviewCount, variant: "caption"),
    ]),
    Row(gap: 12.0, children: [
      Text(text: args.distance, variant: "caption"),
      Text(text: args.deliveryTime, variant: "caption"),
    ]),
  ]),
]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "RestaurantCard": {
      "properties": {
        "image": {
          "$ref": "DynamicString"
        },
        "name": {
          "$ref": "DynamicString"
        },
        "priceRange": {
          "$ref": "DynamicString"
        },
        "cuisine": {
          "$ref": "DynamicString"
        },
        "rating": {
          "$ref": "DynamicString"
        },
        "reviewCount": {
          "$ref": "DynamicString"
        },
        "distance": {
          "$ref": "DynamicString"
        },
        "deliveryTime": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "RestaurantCard",
          "image": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=300&h=150&fit=crop",
          "name": "The Italian Kitchen",
          "priceRange": "$$$",
          "cuisine": "Italian • Pasta • Wine Bar",
          "rating": "4.8",
          "reviewCount": "(2,847 reviews)",
          "distance": "0.8 mi",
          "deliveryTime": "25-35 min"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'account_balance',
    label: 'Account Balance',
    template: r'''
import core;

// An interactive account card. `balance` (in cents) is local state; the two
// buttons deposit and withdraw, computing the new balance with the math
// functions — a withdrawal is clamped at zero with `max`. The balance renders as
// dollars via divide-by-100.
widget AccountBalance { balance: 1245832 } = Card(child: Column(gap: 8.0,
  children: [
    Row(gap: 8.0, crossAxisAlignment: "center", children: [
      Icon(icon: "payment"),
      Text(text: args.accountName),
    ]),
    Heading(text: concat(a: "$", b: divide(a: state.balance, b: 100)), level: 2),
    Text(text: args.lastUpdated, variant: "caption"),
    Divider(),
    Row(gap: 12.0, children: [
      Button(
        onPressed: set state.balance = add(a: state.balance, b: 5000),
        child: Text(text: "Deposit $50")),
      Button(
        onPressed:
          set state.balance = max(a: subtract(a: state.balance, b: 2000), b: 0),
        child: Text(text: "Withdraw $20")),
    ]),
  ]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "AccountBalance": {
      "properties": {
        "accountName": {
          "$ref": "DynamicString"
        },
        "lastUpdated": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "AccountBalance",
          "accountName": "Primary Checking",
          "lastUpdated": "Updated just now"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'shipping_status',
    label: 'Shipping Status',
    template: r'''
import core;

widget ShippingStatus = Card(child: Column(gap: 8.0, children: [
  Row(gap: 8.0, crossAxisAlignment: "center", children: [
    Icon(icon: "info"),
    Text(text: args.title),
  ]),
  Text(text: args.trackingNumber, variant: "caption"),
  Divider(),
  Column(gap: 6.0, children: [
    ...for step in args.steps: Row(gap: 8.0, crossAxisAlignment: "center",
      children: [
        Icon(icon: step.icon),
        Text(text: step.label),
      ]),
  ]),
  Row(gap: 8.0, crossAxisAlignment: "center", children: [
    Icon(icon: "calendarToday"),
    Text(text: args.eta),
  ]),
]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "ShippingStatus": {
      "properties": {
        "title": {
          "$ref": "DynamicString"
        },
        "trackingNumber": {
          "$ref": "DynamicString"
        },
        "eta": {
          "$ref": "DynamicString"
        },
        "steps": {
          "type": "array",
          "items": {
            "type": "object"
          }
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "ShippingStatus",
          "title": "Package Status",
          "trackingNumber": "Tracking: 1Z999AA10123456784",
          "eta": "Estimated delivery: Today by 8 PM",
          "steps": [
            {
              "icon": "check",
              "label": "Order Placed"
            },
            {
              "icon": "check",
              "label": "Shipped"
            },
            {
              "icon": "send",
              "label": "Out for Delivery"
            },
            {
              "icon": "check",
              "label": "Delivered"
            }
          ]
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'flight_status',
    label: 'Flight Status',
    template: r'''
import core;

widget FlightStatus = Card(child: Column(crossAxisAlignment: "stretch",
  gap: 8.0, children: [
    Row(mainAxisAlignment: "spaceBetween", crossAxisAlignment: "center",
      width: "fill", children: [
        Row(gap: 6.0, crossAxisAlignment: "center", children: [
          Icon(icon: "send"),
          Text(text: args.flightNumber),
        ]),
        Text(text: args.date, variant: "caption"),
      ]),
    Row(gap: 8.0, mainAxisAlignment: "center", crossAxisAlignment: "center",
      children: [
        Text(text: args.origin),
        Text(text: "→"),
        Text(text: args.destination),
      ]),
    Divider(),
    Row(mainAxisAlignment: "spaceBetween", width: "fill", children: [
      Column(crossAxisAlignment: "start", gap: 2.0, children: [
        Text(text: "Departs", variant: "caption"),
        Text(text: args.departure),
      ]),
      Column(crossAxisAlignment: "center", gap: 2.0, children: [
        Text(text: "Status", variant: "caption"),
        Text(text: args.status),
      ]),
      Column(crossAxisAlignment: "end", gap: 2.0, children: [
        Text(text: "Arrives", variant: "caption"),
        Text(text: args.arrival),
      ]),
    ]),
  ]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "FlightStatus": {
      "properties": {
        "flightNumber": {
          "$ref": "DynamicString"
        },
        "date": {
          "$ref": "DynamicString"
        },
        "origin": {
          "$ref": "DynamicString"
        },
        "destination": {
          "$ref": "DynamicString"
        },
        "departure": {
          "$ref": "DynamicString"
        },
        "status": {
          "$ref": "DynamicString"
        },
        "arrival": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "FlightStatus",
          "flightNumber": "OS 87",
          "date": "Mon, Dec 15",
          "origin": "Vienna",
          "destination": "New York",
          "departure": "10:15 AM",
          "status": "On Time",
          "arrival": "2:30 PM"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'purchase_complete',
    label: 'Purchase Complete',
    template: r'''
import core;

widget PurchaseComplete = Card(child: Column(crossAxisAlignment: "center",
  gap: 8.0, children: [
    Icon(icon: "check"),
    Text(text: args.title),
    Row(gap: 10.0, crossAxisAlignment: "center", children: [
      Image(url: args.productImage, variant: "smallFeature", fit: "cover"),
      Column(gap: 2.0, children: [
        Text(text: args.productName),
        Text(text: args.price),
      ]),
    ]),
    Divider(),
    Column(gap: 4.0, children: [
      Row(gap: 6.0, crossAxisAlignment: "center", children: [
        Icon(icon: "arrowForward"),
        Text(text: args.delivery),
      ]),
      Row(gap: 6.0, children: [
        Text(text: "Sold by:", variant: "caption"),
        Text(text: args.seller),
      ]),
    ]),
    Button(child: Text(text: args.cta)),
  ]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "PurchaseComplete": {
      "properties": {
        "title": {
          "$ref": "DynamicString"
        },
        "productImage": {
          "$ref": "DynamicString"
        },
        "productName": {
          "$ref": "DynamicString"
        },
        "price": {
          "$ref": "DynamicString"
        },
        "delivery": {
          "$ref": "DynamicString"
        },
        "seller": {
          "$ref": "DynamicString"
        },
        "cta": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "PurchaseComplete",
          "title": "Purchase Complete",
          "productImage": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=100&h=100&fit=crop",
          "productName": "Wireless Headphones Pro",
          "price": "$199.99",
          "delivery": "Arrives Dec 18 - Dec 20",
          "seller": "TechStore Official",
          "cta": "View Order Details"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'coffee_order',
    label: 'Coffee Order',
    template: r'''
import core;

// One cart line: name, size, a −/+ quantity stepper, and a live line total. The
// quantity comes from the parent's state (so the parent can sum the lines) and
// the stepper handlers are passed in, so the line widget itself is stateless.
widget Line = Row(mainAxisAlignment: "spaceBetween", crossAxisAlignment: "center",
  width: "fill", children: [
    Column(children: [
      Text(text: args.name),
      Text(text: args.size, variant: "caption"),
    ]),
    Row(gap: 10.0, crossAxisAlignment: "center", children: [
      Button(onPressed: args.dec, child: Text(text: "−")),
      Text(text: args.qty),
      Button(onPressed: args.inc, child: Text(text: "+")),
      Text(text: args.lineTotal),
    ]),
  ]);

// An interactive coffee order. Each item's quantity is local state; the parent
// holds both quantities so it can sum the line totals into the order total, all
// with the math functions (multiply for a line, add for the sum, max to clamp a
// quantity at zero). Prices are whole dollars.
widget CoffeeOrder { qty1: 1, qty2: 1 } = Card(child: Column(gap: 8.0, children: [
  Row(gap: 6.0, crossAxisAlignment: "center", children: [
    Icon(icon: "favorite"),
    Text(text: args.storeName),
  ]),
  Line(
    name: args.name1,
    size: args.size1,
    qty: state.qty1,
    dec: set state.qty1 = max(a: subtract(a: state.qty1, b: 1), b: 0),
    inc: set state.qty1 = add(a: state.qty1, b: 1),
    lineTotal: concat(a: "$", b: multiply(a: args.price1, b: state.qty1))),
  Line(
    name: args.name2,
    size: args.size2,
    qty: state.qty2,
    dec: set state.qty2 = max(a: subtract(a: state.qty2, b: 1), b: 0),
    inc: set state.qty2 = add(a: state.qty2, b: 1),
    lineTotal: concat(a: "$", b: multiply(a: args.price2, b: state.qty2))),
  Divider(),
  Row(mainAxisAlignment: "spaceBetween", width: "fill", children: [
    Text(text: "Total"),
    Text(text: concat(a: "$", b: add(
      a: multiply(a: args.price1, b: state.qty1),
      b: multiply(a: args.price2, b: state.qty2)))),
  ]),
  Button(child: Text(text: "Checkout")),
]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "CoffeeOrder": {
      "properties": {
        "storeName": {
          "$ref": "DynamicString"
        },
        "name1": {
          "$ref": "DynamicString"
        },
        "size1": {
          "$ref": "DynamicString"
        },
        "price1": {
          "type": "integer"
        },
        "name2": {
          "$ref": "DynamicString"
        },
        "size2": {
          "$ref": "DynamicString"
        },
        "price2": {
          "type": "integer"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "CoffeeOrder",
          "storeName": "Sunrise Coffee",
          "name1": "Oat Milk Latte",
          "size1": "Grande",
          "price1": 6,
          "name2": "Chocolate Croissant",
          "size2": "Warmed",
          "price2": 4
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'credit_card',
    label: 'Credit Card',
    template: r'''
import core;

widget CreditCard = Card(child: Column(gap: 12.0, children: [
  Row(mainAxisAlignment: "spaceBetween", crossAxisAlignment: "center",
    width: "fill", children: [
      Icon(icon: "payment"),
      Text(text: args.cardType),
    ]),
  Text(text: args.cardNumber),
  Row(mainAxisAlignment: "spaceBetween", width: "fill", children: [
    Column(gap: 2.0, children: [
      Text(text: "CARD HOLDER", variant: "caption"),
      Text(text: args.holderName),
    ]),
    Column(crossAxisAlignment: "end", gap: 2.0, children: [
      Text(text: "EXPIRES", variant: "caption"),
      Text(text: args.expiryDate),
    ]),
  ]),
]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "CreditCard": {
      "properties": {
        "cardType": {
          "$ref": "DynamicString"
        },
        "cardNumber": {
          "$ref": "DynamicString"
        },
        "holderName": {
          "$ref": "DynamicString"
        },
        "expiryDate": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "CreditCard",
          "cardType": "VISA",
          "cardNumber": "•••• •••• •••• 4242",
          "holderName": "SARAH JOHNSON",
          "expiryDate": "09/27"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'child_list_template',
    label: 'Child List Template',
    template: r'''
import core;

widget ItemList = Card(child: Column(crossAxisAlignment: "stretch", gap: 8.0,
  children: [
    Text(text: args.title),
    List(direction: "vertical", children: [
      ...for item in args.items: Row(gap: 4.0, children: [
        Text(text: item.name),
        Text(text: " - Qty: "),
        Text(text: item.quantity),
      ]),
    ]),
  ]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "ItemList": {
      "properties": {
        "title": {
          "$ref": "DynamicString"
        },
        "items": {
          "type": "array",
          "items": {
            "type": "object"
          }
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "ItemList",
          "title": "Dynamic Item List",
          "items": [
            {
              "name": "Apple",
              "quantity": "10"
            },
            {
              "name": "Banana",
              "quantity": "5"
            },
            {
              "name": "Cherry",
              "quantity": "20"
            }
          ]
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'markdown_text',
    label: 'Markdown',
    template: r'''
import core;

widget MarkdownText = Card(child: Column(crossAxisAlignment: "stretch",
  gap: 8.0, children: [
    Text(text: args.title),
    Markdown(text: args.content),
  ]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "MarkdownText": {
      "properties": {
        "title": {
          "$ref": "DynamicString"
        },
        "content": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "MarkdownText",
          "title": "Markdown Rendering",
          "content": "# Heading 1\n\nThis is **bold** text and *italic* text.\n\n- List item 1\n- List item 2\n\n[Link to Google](https://google.com)"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'music_player',
    label: 'Music Player',
    template: r'''
import core;

widget MusicPlayer = Card(child: Column(crossAxisAlignment: "center", gap: 8.0,
  children: [
    Image(url: args.albumArt, variant: "mediumFeature", fit: "cover"),
    Column(crossAxisAlignment: "center", gap: 2.0, children: [
      Heading(text: args.title, level: 2),
      Text(text: args.artist, variant: "caption"),
    ]),
    Slider(value: 0.45, min: 0.0, max: 1.0),
    Row(mainAxisAlignment: "spaceBetween", width: "fill", children: [
      Text(text: args.currentTime, variant: "caption"),
      Text(text: args.totalTime, variant: "caption"),
    ]),
    Row(mainAxisAlignment: "center", gap: 16.0, children: [
      Button(child: Icon(icon: "skipPrevious")),
      Button(child: Icon(icon: args.playIcon)),
      Button(child: Icon(icon: "skipNext")),
    ]),
  ]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "MusicPlayer": {
      "properties": {
        "albumArt": {
          "$ref": "DynamicString"
        },
        "title": {
          "$ref": "DynamicString"
        },
        "artist": {
          "$ref": "DynamicString"
        },
        "currentTime": {
          "$ref": "DynamicString"
        },
        "totalTime": {
          "$ref": "DynamicString"
        },
        "playIcon": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "MusicPlayer",
          "albumArt": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop",
          "title": "Blinding Lights",
          "artist": "The Weeknd",
          "currentTime": "1:48",
          "totalTime": "4:22",
          "playIcon": "pause"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'notification_permission',
    label: 'Permission',
    template: r'''
import core;

widget NotificationPermission = Card(child: Column(crossAxisAlignment: "center",
  gap: 8.0, children: [
    Icon(icon: args.icon),
    Heading(text: args.title, level: 2),
    Text(text: args.description),
    Row(mainAxisAlignment: "center", gap: 12.0, children: [
      Button(child: Text(text: args.acceptLabel)),
      Button(child: Text(text: args.declineLabel)),
    ]),
  ]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "NotificationPermission": {
      "properties": {
        "icon": {
          "$ref": "DynamicString"
        },
        "title": {
          "$ref": "DynamicString"
        },
        "description": {
          "$ref": "DynamicString"
        },
        "acceptLabel": {
          "$ref": "DynamicString"
        },
        "declineLabel": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "NotificationPermission",
          "icon": "notifications",
          "title": "Enable notifications",
          "description": "Get alerts for order status changes",
          "acceptLabel": "Yes",
          "declineLabel": "No"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'sports_player',
    label: 'Sports Player',
    template: r'''
import core;

widget Stat = Column(crossAxisAlignment: "center", gap: 2.0, children: [
  Text(text: args.value),
  Text(text: args.label, variant: "caption"),
]);

widget SportsPlayer = Card(child: Column(crossAxisAlignment: "center", gap: 8.0,
  children: [
    Image(url: args.image, variant: "avatar", fit: "cover"),
    Column(crossAxisAlignment: "center", gap: 2.0, children: [
      Heading(text: args.name, level: 2),
      Row(gap: 8.0, crossAxisAlignment: "center", children: [
        Text(text: args.number),
        Text(text: args.team, variant: "caption"),
      ]),
    ]),
    Divider(),
    Row(mainAxisAlignment: "spaceAround", width: "fill", children: [
      Stat(value: args.stat1Value, label: args.stat1Label),
      Stat(value: args.stat2Value, label: args.stat2Label),
      Stat(value: args.stat3Value, label: args.stat3Label),
    ]),
  ]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "Stat": {
      "properties": {
        "value": {
          "$ref": "DynamicString"
        },
        "label": {
          "$ref": "DynamicString"
        }
      }
    },
    "SportsPlayer": {
      "properties": {
        "image": {
          "$ref": "DynamicString"
        },
        "name": {
          "$ref": "DynamicString"
        },
        "number": {
          "$ref": "DynamicString"
        },
        "team": {
          "$ref": "DynamicString"
        },
        "stat1Value": {
          "$ref": "DynamicString"
        },
        "stat1Label": {
          "$ref": "DynamicString"
        },
        "stat2Value": {
          "$ref": "DynamicString"
        },
        "stat2Label": {
          "$ref": "DynamicString"
        },
        "stat3Value": {
          "$ref": "DynamicString"
        },
        "stat3Label": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "SportsPlayer",
          "image": "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=200&h=200&fit=crop",
          "name": "Marcus Johnson",
          "number": "#23",
          "team": "LA Lakers",
          "stat1Value": "28.4",
          "stat1Label": "PPG",
          "stat2Value": "7.2",
          "stat2Label": "RPG",
          "stat3Value": "6.8",
          "stat3Label": "APG"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'event_detail',
    label: 'Event Detail',
    template: r'''
import core;

widget EventDetail = Card(child: Column(gap: 8.0, children: [
  Heading(text: args.title, level: 2),
  Row(gap: 6.0, crossAxisAlignment: "center", children: [
    Icon(icon: "calendarToday"),
    Text(text: args.time),
  ]),
  Row(gap: 6.0, crossAxisAlignment: "center", children: [
    Icon(icon: "locationOn"),
    Text(text: args.location),
  ]),
  Text(text: args.description),
  Divider(),
  Row(gap: 12.0, children: [
    Button(child: Text(text: args.acceptLabel)),
    Button(child: Text(text: args.declineLabel)),
  ]),
]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "EventDetail": {
      "properties": {
        "title": {
          "$ref": "DynamicString"
        },
        "time": {
          "$ref": "DynamicString"
        },
        "location": {
          "$ref": "DynamicString"
        },
        "description": {
          "$ref": "DynamicString"
        },
        "acceptLabel": {
          "$ref": "DynamicString"
        },
        "declineLabel": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "EventDetail",
          "title": "Product Launch Meeting",
          "time": "Fri, Dec 19 • 2:00 PM - 3:30 PM",
          "location": "Conference Room A, Building 2",
          "description": "Review final product specs and marketing materials before the Q1 launch.",
          "acceptLabel": "Accept",
          "declineLabel": "Decline"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'step_counter',
    label: 'Step Counter',
    template: r'''
import core;

widget Stat = Column(crossAxisAlignment: "center", gap: 2.0, children: [
  Text(text: args.value),
  Text(text: args.label, variant: "caption"),
]);

// An interactive step tracker. `steps` is local state; everything else is
// *derived* from it with the standard math functions — progress toward a
// 10,000-step goal (steps × 100 ÷ 10,000, capped at 100 with `min`), distance
// (steps ÷ 2,000 miles), and calories (steps × 0.04, rounded). Tapping
// "Log 500 steps" bumps the state and the whole card recomputes, identically on
// every adapter.
widget StepCounter { steps: 0 } = Card(child: Column(
  crossAxisAlignment: "center",
  gap: 8.0,
  children: [
    Row(gap: 6.0, crossAxisAlignment: "center", children: [
      Icon(icon: "person"),
      Heading(text: args.title, level: 3),
    ]),
    Heading(text: state.steps, level: 1),
    Text(
      text: concat(
        a: min(a: divide(a: multiply(a: state.steps, b: 100), b: 10000), b: 100),
        b: "% of 10,000 step goal"),
      variant: "caption"),
    Divider(),
    Row(mainAxisAlignment: "spaceAround", width: "fill", children: [
      Stat(
        value: concat(a: divide(a: state.steps, b: 2000), b: " mi"),
        label: "Distance"),
      Stat(
        value: round(value: multiply(a: state.steps, b: 0.04)),
        label: "Calories"),
    ]),
    Button(
      onPressed: set state.steps = add(a: state.steps, b: 500),
      child: Text(text: "Log 500 steps")),
  ]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "Stat": {
      "properties": {
        "value": {
          "$ref": "DynamicString"
        },
        "label": {
          "$ref": "DynamicString"
        }
      }
    },
    "StepCounter": {
      "properties": {
        "title": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "StepCounter",
          "title": "Today's Activity"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'countdown_timer',
    label: 'Countdown',
    template: r'''
import core;

widget Unit = Column(crossAxisAlignment: "center", gap: 2.0, children: [
  Text(text: args.value),
  Text(text: args.label, variant: "caption"),
]);

widget CountdownTimer = Card(child: Column(crossAxisAlignment: "center",
  gap: 8.0, children: [
    Heading(text: args.eventName, level: 2),
    Row(mainAxisAlignment: "spaceAround", width: "fill", children: [
      Unit(value: args.days, label: "Days"),
      Unit(value: args.hours, label: "Hours"),
      Unit(value: args.minutes, label: "Minutes"),
    ]),
    Text(text: args.targetDate),
  ]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "Unit": {
      "properties": {
        "value": {
          "$ref": "DynamicString"
        },
        "label": {
          "$ref": "DynamicString"
        }
      }
    },
    "CountdownTimer": {
      "properties": {
        "eventName": {
          "$ref": "DynamicString"
        },
        "days": {
          "$ref": "DynamicString"
        },
        "hours": {
          "$ref": "DynamicString"
        },
        "minutes": {
          "$ref": "DynamicString"
        },
        "targetDate": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "CountdownTimer",
          "eventName": "Product Launch",
          "days": "14",
          "hours": "08",
          "minutes": "32",
          "targetDate": "January 15, 2025"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'row_layout',
    label: 'Row Layout',
    template: r'''
import core;

widget RowLayout = Row(mainAxisAlignment: "spaceBetween",
  crossAxisAlignment: "center", width: "fill", children: [
    Text(text: args.left),
    Text(text: args.right, variant: "caption"),
  ]);
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "RowLayout": {
      "properties": {
        "left": {
          "$ref": "DynamicString"
        },
        "right": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "RowLayout",
          "left": "Left Content",
          "right": "Right Content"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'user_profile',
    label: 'User Profile',
    template: r'''
import core;

widget Stat = Column(crossAxisAlignment: "center", gap: 2.0, children: [
  Text(text: args.value),
  Text(text: args.label, variant: "caption"),
]);

widget UserProfile = Card(child: Column(crossAxisAlignment: "center", gap: 8.0,
  children: [
    Image(url: args.avatar, variant: "avatar", fit: "cover"),
    Column(crossAxisAlignment: "center", gap: 2.0, children: [
      Heading(text: args.name, level: 2),
      Text(text: args.username, variant: "caption"),
    ]),
    Text(text: args.bio),
    Row(mainAxisAlignment: "spaceAround", width: "fill", children: [
      Stat(value: args.followers, label: "Followers"),
      Stat(value: args.following, label: "Following"),
      Stat(value: args.posts, label: "Posts"),
    ]),
    Button(child: Text(text: args.followText)),
  ]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "UserProfile": {
      "properties": {
        "avatar": {
          "$ref": "DynamicString"
        },
        "name": {
          "$ref": "DynamicString"
        },
        "username": {
          "$ref": "DynamicString"
        },
        "bio": {
          "$ref": "DynamicString"
        },
        "followers": {
          "$ref": "DynamicString"
        },
        "following": {
          "$ref": "DynamicString"
        },
        "posts": {
          "$ref": "DynamicString"
        },
        "followText": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "UserProfile",
          "avatar": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop",
          "name": "Sarah Chen",
          "username": "@sarahchen",
          "bio": "Product Designer at Tech Co. Creating delightful experiences.",
          "followers": "12.4K",
          "following": "892",
          "posts": "347",
          "followText": "Follow"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'chat_message',
    label: 'Chat',
    template: r'''
import core;

widget ChatMessage = Card(child: Column(gap: 8.0, children: [
  Row(gap: 6.0, crossAxisAlignment: "center", children: [
    Icon(icon: "info"),
    Heading(text: args.channelName, level: 3),
  ]),
  Divider(),
  Column(gap: 10.0, children: [
    ...for msg in args.messages: Row(gap: 8.0, crossAxisAlignment: "start",
      children: [
        Image(url: msg.avatar, variant: "avatar", fit: "cover"),
        // A fixed width bounds the message body so it wraps, instead of forcing
        // the row as wide as the longest line.
        SizedBox(width: 240.0, child: Column(gap: 2.0, children: [
          Row(gap: 6.0, crossAxisAlignment: "center", children: [
            Text(text: msg.username),
            Text(text: msg.time, variant: "caption"),
          ]),
          Text(text: msg.text),
        ])),
      ]),
  ]),
]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "ChatMessage": {
      "properties": {
        "channelName": {
          "$ref": "DynamicString"
        },
        "messages": {
          "type": "array",
          "items": {
            "type": "object"
          }
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "ChatMessage",
          "channelName": "project-updates",
          "messages": [
            {
              "avatar": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=40&h=40&fit=crop",
              "username": "Mike Chen",
              "time": "10:32 AM",
              "text": "Just pushed the new API changes. Ready for review."
            },
            {
              "avatar": "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=40&h=40&fit=crop",
              "username": "Sarah Kim",
              "time": "10:45 AM",
              "text": "Great! I'll take a look after standup."
            }
          ]
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'workout_summary',
    label: 'Workout',
    template: r'''
import core;

widget Metric = Column(crossAxisAlignment: "center", gap: 2.0, children: [
  Text(text: args.value),
  Text(text: args.label, variant: "caption"),
]);

widget WorkoutSummary = Card(child: Column(crossAxisAlignment: "center",
  gap: 8.0, children: [
    Row(gap: 6.0, crossAxisAlignment: "center", children: [
      Icon(icon: "directions_run"),
      Heading(text: args.title, level: 3),
    ]),
    Divider(),
    Row(mainAxisAlignment: "spaceAround", width: "fill", children: [
      Metric(value: args.duration, label: "Duration"),
      Metric(value: args.calories, label: "Calories"),
      Metric(value: args.distance, label: "Distance"),
    ]),
    Text(text: args.date, variant: "caption"),
  ]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "WorkoutSummary": {
      "properties": {
        "title": {
          "$ref": "DynamicString"
        },
        "duration": {
          "$ref": "DynamicString"
        },
        "calories": {
          "$ref": "DynamicString"
        },
        "distance": {
          "$ref": "DynamicString"
        },
        "date": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "WorkoutSummary",
          "title": "Workout Complete",
          "duration": "32:15",
          "calories": "385",
          "distance": "5.2 km",
          "date": "Monday, Dec 15 at 7:30 AM"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'track_list',
    label: 'Track List',
    template: r'''
import core;

widget TrackList = Card(child: Column(crossAxisAlignment: "stretch", gap: 8.0,
  children: [
    Row(gap: 6.0, crossAxisAlignment: "center", children: [
      Icon(icon: "play"),
      Heading(text: args.playlistName, level: 3),
    ]),
    Divider(),
    Column(gap: 8.0, children: [
      ...for track in args.tracks: Row(gap: 8.0, crossAxisAlignment: "center",
        children: [
          Text(text: track.number, variant: "caption"),
          Image(url: track.art, variant: "avatar", fit: "cover"),
          Expanded(child: Column(gap: 2.0, children: [
            Text(text: track.title),
            Text(text: track.artist, variant: "caption"),
          ])),
          Text(text: track.duration, variant: "caption"),
        ]),
    ]),
  ]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "TrackList": {
      "properties": {
        "playlistName": {
          "$ref": "DynamicString"
        },
        "tracks": {
          "type": "array",
          "items": {
            "type": "object"
          }
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "TrackList",
          "playlistName": "Focus Flow",
          "tracks": [
            {
              "number": "1",
              "art": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=50&h=50&fit=crop",
              "title": "Weightless",
              "artist": "Marconi Union",
              "duration": "8:09"
            },
            {
              "number": "2",
              "art": "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=50&h=50&fit=crop",
              "title": "Clair de Lune",
              "artist": "Debussy",
              "duration": "5:12"
            },
            {
              "number": "3",
              "art": "https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=50&h=50&fit=crop",
              "title": "Ambient Light",
              "artist": "Brian Eno",
              "duration": "6:45"
            }
          ]
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'financial_data_grid',
    label: 'Data Grid',
    template: r'''
import core;

widget HeaderRow = Row(crossAxisAlignment: "center", children: [
  Expanded(flex: 4, child: Text(text: "Asset", variant: "caption")),
  Expanded(flex: 2, child: Text(text: "Price", variant: "caption")),
  Expanded(flex: 2, child: Text(text: "24h", variant: "caption")),
  Expanded(flex: 3, child: Text(text: "Mkt Cap", variant: "caption")),
]);

widget AssetRow = Row(crossAxisAlignment: "center", children: [
  Expanded(flex: 4, child: Row(gap: 6.0, crossAxisAlignment: "center",
    children: [
      Icon(icon: "payment"),
      Column(gap: 1.0, children: [
        Text(text: args.name),
        Text(text: args.symbol, variant: "caption"),
      ]),
    ])),
  Expanded(flex: 2, child: Text(text: args.price)),
  Expanded(flex: 2, child: Text(text: args.change)),
  Expanded(flex: 3, child: Text(text: args.marketCap, variant: "caption")),
]);

widget FinancialGrid = Card(child: Column(crossAxisAlignment: "stretch",
  gap: 6.0, children: [
    HeaderRow(),
    Divider(),
    ...for asset in args.assets: AssetRow(name: asset.name, symbol: asset.symbol,
      price: asset.price, change: asset.change, marketCap: asset.marketCap),
  ]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "FinancialGrid": {
      "properties": {
        "assets": {
          "type": "array",
          "items": {
            "type": "object"
          }
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "FinancialGrid",
          "assets": [
            {
              "name": "Bitcoin",
              "symbol": "BTC",
              "price": "$43,500.25",
              "change": "+1.2%",
              "marketCap": "$850.0B"
            },
            {
              "name": "Ethereum",
              "symbol": "ETH",
              "price": "$2,250.50",
              "change": "-0.5%",
              "marketCap": "$270.0B"
            },
            {
              "name": "Solana",
              "symbol": "SOL",
              "price": "$95.80",
              "change": "+5.4%",
              "marketCap": "$40.0B"
            }
          ]
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'formatted_text',
    label: 'Formatted Text',
    template: r'''
import core;

widget Labelled = Column(gap: 4.0, children: [
  Text(text: args.label, variant: "caption"),
  TextField(value: args.value),
]);

widget FormattedText = Column(crossAxisAlignment: "stretch", gap: 8.0,
  children: [
    Labelled(label: args.inputLabel, value: args.inputValue),
    Text(text: args.resultLabel, variant: "caption"),
    Text(text: args.result),
  ]);
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "FormattedText": {
      "properties": {
        "inputLabel": {
          "$ref": "DynamicString"
        },
        "inputValue": {
          "$ref": "DynamicString"
        },
        "resultLabel": {
          "$ref": "DynamicString"
        },
        "result": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "FormattedText",
          "inputLabel": "Type something:",
          "inputValue": "hello",
          "resultLabel": "Formatted output:",
          "result": "You typed: hello"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'incremental',
    label: 'Incremental',
    template: r'''
import core;

widget RestaurantItem = Card(child: Column(gap: 4.0, children: [
  Heading(text: args.title, level: 3),
  Text(text: args.subtitle, variant: "caption"),
  Text(text: args.address, variant: "caption"),
  Button(child: Text(text: "Book now")),
]));

widget Incremental = Column(crossAxisAlignment: "stretch", gap: 10.0,
  children: [
    ...for r in args.restaurants: RestaurantItem(title: r.title,
      subtitle: r.subtitle, address: r.address),
  ]);
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "Incremental": {
      "properties": {
        "restaurants": {
          "type": "array",
          "items": {
            "type": "object"
          }
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "Incremental",
          "restaurants": [
            {
              "title": "The Golden Fork",
              "subtitle": "Fine Dining & Spirits",
              "address": "123 Gastronomy Lane"
            },
            {
              "title": "Ocean's Bounty",
              "subtitle": "Fresh Daily Seafood",
              "address": "456 Shoreline Dr"
            },
            {
              "title": "Pizzeria Roma",
              "subtitle": "Authentic Wood-Fired Pizza",
              "address": "789 Napoli Way"
            },
            {
              "title": "Spice Route",
              "subtitle": "Exotic Flavors from the East",
              "address": "101 Silk Road St"
            }
          ]
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'complex_layout',
    label: 'Complex Layout',
    template: r'''
import core;

widget Labelled = Column(gap: 4.0, children: [
  Text(text: args.label, variant: "caption"),
  TextField(value: args.value),
]);

widget ComplexLayout = SizedBox(width: 360.0, child: Column(
  crossAxisAlignment: "stretch", gap: 12.0, children: [
    Heading(text: args.title, level: 2),
    Row(gap: 12.0, crossAxisAlignment: "start", children: [
      Expanded(child: Labelled(label: args.firstLabel, value: args.firstValue)),
      Expanded(child: Labelled(label: args.lastLabel, value: args.lastValue)),
    ]),
    Text(text: args.footer, variant: "caption"),
  ]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "ComplexLayout": {
      "properties": {
        "title": {
          "$ref": "DynamicString"
        },
        "firstLabel": {
          "$ref": "DynamicString"
        },
        "firstValue": {
          "$ref": "DynamicString"
        },
        "lastLabel": {
          "$ref": "DynamicString"
        },
        "lastValue": {
          "$ref": "DynamicString"
        },
        "footer": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "ComplexLayout",
          "title": "User Profile Form",
          "firstLabel": "First Name",
          "firstValue": "",
          "lastLabel": "Last Name",
          "lastValue": "",
          "footer": "Please fill out all fields."
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'email_compose',
    label: 'Email Compose',
    template: r'''
import core;

widget Field = Column(gap: 1.0, children: [
  Text(text: args.label, variant: "caption"),
  Text(text: args.value),
]);

widget EmailCompose = SizedBox(width: 360.0, child: Card(child: Column(
  crossAxisAlignment: "stretch", gap: 6.0, children: [
    Field(label: "FROM", value: args.from),
    Field(label: "TO", value: args.to),
    Field(label: "SUBJECT", value: args.subject),
    Divider(),
    Column(gap: 6.0, children: [
      Text(text: args.greeting),
      Text(text: args.body),
      Text(text: args.closing),
      Text(text: args.signature),
    ]),
    Row(gap: 12.0, children: [
      Button(child: Text(text: "Send email")),
      Button(child: Text(text: "Discard")),
    ]),
  ])));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "EmailCompose": {
      "properties": {
        "from": {
          "$ref": "DynamicString"
        },
        "to": {
          "$ref": "DynamicString"
        },
        "subject": {
          "$ref": "DynamicString"
        },
        "greeting": {
          "$ref": "DynamicString"
        },
        "body": {
          "$ref": "DynamicString"
        },
        "closing": {
          "$ref": "DynamicString"
        },
        "signature": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "EmailCompose",
          "from": "alex@acme.com",
          "to": "jordan@acme.com",
          "subject": "Q4 Revenue Forecast",
          "greeting": "Hi Jordan,",
          "body": "Following up on our call. Please review the attached Q4 forecast and let me know if you have questions before the board meeting.",
          "closing": "Best,",
          "signature": "Alex"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'calendar_day',
    label: 'Calendar Day',
    template: r'''
import core;

widget EventItem = Column(gap: 1.0, children: [
  Text(text: args.title),
  Text(text: args.time, variant: "caption"),
]);

widget CalendarDay = Card(child: Column(crossAxisAlignment: "stretch", gap: 8.0,
  children: [
    Row(gap: 16.0, crossAxisAlignment: "start", children: [
      Column(crossAxisAlignment: "center", gap: 2.0, children: [
        Text(text: args.dayName, variant: "caption"),
        Heading(text: args.dayNumber, level: 1),
      ]),
      Expanded(child: Column(gap: 6.0, children: [
        ...for e in args.events: EventItem(title: e.title, time: e.time),
      ])),
    ]),
    Divider(),
    Row(gap: 12.0, children: [
      Button(child: Text(text: "Add to calendar")),
      Button(child: Text(text: "Discard")),
    ]),
  ]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "CalendarDay": {
      "properties": {
        "dayName": {
          "$ref": "DynamicString"
        },
        "dayNumber": {
          "$ref": "DynamicString"
        },
        "events": {
          "type": "array",
          "items": {
            "type": "object"
          }
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "CalendarDay",
          "dayName": "Sunday",
          "dayNumber": "28",
          "events": [
            {
              "title": "Lunch",
              "time": "12:00 - 12:45 PM"
            },
            {
              "title": "Q1 roadmap review",
              "time": "1:00 - 2:00 PM"
            },
            {
              "title": "Team standup",
              "time": "3:30 - 4:00 PM"
            }
          ]
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'sign_in',
    label: 'Sign In',
    template: r'''
import core;

widget Labelled = Column(gap: 4.0, children: [
  Text(text: args.label, variant: "caption"),
  TextField(value: args.value),
]);

widget SignIn = Card(child: Column(crossAxisAlignment: "stretch", gap: 10.0,
  children: [
    Column(crossAxisAlignment: "center", gap: 2.0, children: [
      Heading(text: args.title, level: 2),
      Text(text: args.subtitle, variant: "caption"),
    ]),
    Labelled(label: args.emailLabel, value: args.email),
    Labelled(label: args.passwordLabel, value: args.password),
    Button(child: Text(text: args.submitLabel)),
    Divider(),
    Row(mainAxisAlignment: "center", gap: 6.0, crossAxisAlignment: "center",
      children: [
        Text(text: args.signupPrompt, variant: "caption"),
        Button(child: Text(text: args.signupLabel)),
      ]),
  ]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "SignIn": {
      "properties": {
        "title": {
          "$ref": "DynamicString"
        },
        "subtitle": {
          "$ref": "DynamicString"
        },
        "emailLabel": {
          "$ref": "DynamicString"
        },
        "email": {
          "$ref": "DynamicString"
        },
        "passwordLabel": {
          "$ref": "DynamicString"
        },
        "password": {
          "$ref": "DynamicString"
        },
        "submitLabel": {
          "$ref": "DynamicString"
        },
        "signupPrompt": {
          "$ref": "DynamicString"
        },
        "signupLabel": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "SignIn",
          "title": "Welcome back",
          "subtitle": "Sign in to your account",
          "emailLabel": "Email",
          "email": "",
          "passwordLabel": "Password",
          "password": "",
          "submitLabel": "Sign in",
          "signupPrompt": "Don't have an account?",
          "signupLabel": "Sign up"
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'incremental_dashboard',
    label: 'Dashboard',
    template: r'''
import core;

widget Dashboard = Column(crossAxisAlignment: "stretch", gap: 10.0, children: [
  Heading(text: args.title, level: 2),
  Row(gap: 12.0, crossAxisAlignment: "start", children: [
    Expanded(child: Card(child: Column(crossAxisAlignment: "stretch", gap: 4.0,
      children: [
        Heading(text: args.analyticsTitle, level: 4),
        Text(text: args.analyticsText),
      ]))),
    Expanded(child: Card(child: Column(crossAxisAlignment: "stretch", gap: 4.0,
      children: [
        Heading(text: args.logsTitle, level: 4),
        ...for log in args.logs: Text(text: log.message, variant: "caption"),
      ]))),
  ]),
]);
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "Dashboard": {
      "properties": {
        "title": {
          "$ref": "DynamicString"
        },
        "analyticsTitle": {
          "$ref": "DynamicString"
        },
        "analyticsText": {
          "$ref": "DynamicString"
        },
        "logsTitle": {
          "$ref": "DynamicString"
        },
        "logs": {
          "type": "array",
          "items": {
            "type": "object"
          }
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "Dashboard",
          "title": "System Dashboard",
          "analyticsTitle": "Analytics",
          "analyticsText": "Analytics are ready.",
          "logsTitle": "Logs",
          "logs": [
            {
              "message": "System boot complete."
            },
            {
              "message": "All services healthy."
            },
            {
              "message": "Waiting for user input."
            }
          ]
        }
      ]
    }
  }
]
''',
  ),
  RawSample(
    id: 'form_validator',
    label: 'Form Validator',
    template: r'''
import core;

widget Labelled = Column(gap: 4.0, children: [
  Text(text: args.label, variant: "caption"),
  TextField(value: args.value),
]);

widget FormValidator = Card(child: Column(crossAxisAlignment: "stretch",
  gap: 10.0, children: [
    Text(text: args.welcome),
    Labelled(label: args.emailLabel, value: args.email),
    Labelled(label: args.phoneLabel, value: args.phone),
    Labelled(label: args.zipLabel, value: args.zip),
    Row(gap: 8.0, crossAxisAlignment: "center", children: [
      Checkbox(value: args.agree),
      Expanded(child: Text(text: args.termsLabel, variant: "caption")),
    ]),
    Button(child: Text(text: args.submitLabel)),
  ]));
''',
    schema: r'''
{
  "catalogId": "demo",
  "components": {
    "FormValidator": {
      "properties": {
        "welcome": {
          "$ref": "DynamicString"
        },
        "emailLabel": {
          "$ref": "DynamicString"
        },
        "email": {
          "$ref": "DynamicString"
        },
        "phoneLabel": {
          "$ref": "DynamicString"
        },
        "phone": {
          "$ref": "DynamicString"
        },
        "zipLabel": {
          "$ref": "DynamicString"
        },
        "zip": {
          "$ref": "DynamicString"
        },
        "agree": {
          "$ref": "DynamicBoolean"
        },
        "termsLabel": {
          "$ref": "DynamicString"
        },
        "submitLabel": {
          "$ref": "DynamicString"
        }
      }
    }
  }
}
''',
    messages: r'''
[
  {
    "version": "v0.9",
    "createSurface": {
      "surfaceId": "demo",
      "catalogId": "demo",
      "sendDataModel": false
    }
  },
  {
    "version": "v0.9",
    "updateComponents": {
      "surfaceId": "demo",
      "components": [
        {
          "id": "root",
          "component": "FormValidator",
          "welcome": "Hello! Today is Monday, December 15.",
          "emailLabel": "Email Address",
          "email": "",
          "phoneLabel": "Phone Number",
          "phone": "",
          "zipLabel": "Zip Code",
          "zip": "",
          "agree": false,
          "termsLabel": "I agree to the terms and conditions",
          "submitLabel": "Submit Registration"
        }
      ]
    }
  }
]
''',
  ),
];

// Named accessors (one per sample), kept for the example apps and tests.
SampleSpec greetingSpec(String framework) => rawSamples[0].toSpec(framework);
SampleSpec counterSpec(String framework) => rawSamples[1].toSpec(framework);
SampleSpec toggleSpec(String framework) => rawSamples[2].toSpec(framework);
SampleSpec calculatorSpec(String framework) => rawSamples[3].toSpec(framework);
SampleSpec boxesSpec(String framework) => rawSamples[4].toSpec(framework);
SampleSpec layoutSpec(String framework) => rawSamples[5].toSpec(framework);
SampleSpec contactCardSpec(String framework) => rawSamples[6].toSpec(framework);
SampleSpec statsCardSpec(String framework) => rawSamples[7].toSpec(framework);
SampleSpec profileCardSpec(String framework) => rawSamples[8].toSpec(framework);
SampleSpec gallerySpec(String framework) => rawSamples[9].toSpec(framework);
SampleSpec formSpec(String framework) => rawSamples[10].toSpec(framework);
SampleSpec simpleTextSpec(String framework) => rawSamples[11].toSpec(framework);
SampleSpec interactiveButtonSpec(String framework) =>
    rawSamples[12].toSpec(framework);
SampleSpec loginFormSpec(String framework) => rawSamples[13].toSpec(framework);
SampleSpec weatherSpec(String framework) => rawSamples[14].toSpec(framework);
SampleSpec productCardSpec(String framework) =>
    rawSamples[15].toSpec(framework);
SampleSpec restaurantCardSpec(String framework) =>
    rawSamples[16].toSpec(framework);
SampleSpec accountBalanceSpec(String framework) =>
    rawSamples[17].toSpec(framework);
SampleSpec shippingStatusSpec(String framework) =>
    rawSamples[18].toSpec(framework);
SampleSpec flightStatusSpec(String framework) =>
    rawSamples[19].toSpec(framework);
SampleSpec purchaseCompleteSpec(String framework) =>
    rawSamples[20].toSpec(framework);
SampleSpec coffeeOrderSpec(String framework) =>
    rawSamples[21].toSpec(framework);
SampleSpec creditCardSpec(String framework) => rawSamples[22].toSpec(framework);
SampleSpec childListTemplateSpec(String framework) =>
    rawSamples[23].toSpec(framework);
SampleSpec markdownTextSpec(String framework) =>
    rawSamples[24].toSpec(framework);
SampleSpec musicPlayerSpec(String framework) =>
    rawSamples[25].toSpec(framework);
SampleSpec notificationPermissionSpec(String framework) =>
    rawSamples[26].toSpec(framework);
SampleSpec sportsPlayerSpec(String framework) =>
    rawSamples[27].toSpec(framework);
SampleSpec eventDetailSpec(String framework) =>
    rawSamples[28].toSpec(framework);
SampleSpec stepCounterSpec(String framework) =>
    rawSamples[29].toSpec(framework);
SampleSpec countdownTimerSpec(String framework) =>
    rawSamples[30].toSpec(framework);
SampleSpec rowLayoutSpec(String framework) => rawSamples[31].toSpec(framework);
SampleSpec userProfileSpec(String framework) =>
    rawSamples[32].toSpec(framework);
SampleSpec chatMessageSpec(String framework) =>
    rawSamples[33].toSpec(framework);
SampleSpec workoutSummarySpec(String framework) =>
    rawSamples[34].toSpec(framework);
SampleSpec trackListSpec(String framework) => rawSamples[35].toSpec(framework);
SampleSpec financialDataGridSpec(String framework) =>
    rawSamples[36].toSpec(framework);
SampleSpec formattedTextSpec(String framework) =>
    rawSamples[37].toSpec(framework);
SampleSpec incrementalSpec(String framework) =>
    rawSamples[38].toSpec(framework);
SampleSpec complexLayoutSpec(String framework) =>
    rawSamples[39].toSpec(framework);
SampleSpec emailComposeSpec(String framework) =>
    rawSamples[40].toSpec(framework);
SampleSpec calendarDaySpec(String framework) =>
    rawSamples[41].toSpec(framework);
SampleSpec signInSpec(String framework) => rawSamples[42].toSpec(framework);
SampleSpec incrementalDashboardSpec(String framework) =>
    rawSamples[43].toSpec(framework);
SampleSpec formValidatorSpec(String framework) =>
    rawSamples[44].toSpec(framework);
